<?php
return [
  [
    'name' => 'CustomGroup_CLIN_Adult_Information',
    'entity' => 'CustomGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'CLIN_Adult_Information',
        'title' => E::ts('CLIN - Adult Information'),
        'extends' => 'Individual',
        'extends_entity_column_value' => [
          'Client',
        ],
        'style' => 'Inline',
        'help_pre' => '',
        'help_post' => '',
        'weight' => 59,
        'collapse_adv_display' => TRUE,
        'created_date' => '2024-05-10 08:33:49',
        'icon' => '',
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Information_Verbal_informed_consent_achieved_',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'CLIN_Adult_Information_Verbal_informed_consent_achieved_',
        'title' => E::ts('CLIN Adult Information :: Verbal informed consent achieved?'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => [
          'name',
          'label',
          'description',
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Information_Verbal_informed_consent_achieved_OptionValue_Verbal_informed_consent_achieve',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Information_Verbal_informed_consent_achieved_',
        'label' => E::ts('Verbal informed consent achieved?'),
        'value' => '1',
        'name' => 'Verbal_informed_consent_achieve',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_Adult_Information_CustomField_Verbal_informed_consent_achieved_',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_Adult_Information',
        'name' => 'Verbal_informed_consent_achieved_',
        'label' => E::ts('Verbal informed consent achieved?'),
        'html_type' => 'CheckBox',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'verbal_informed_consent_achieved_1416',
        'option_group_id.name' => 'CLIN_Adult_Information_Verbal_informed_consent_achieved_',
        'serialize' => 1,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Counselling_Information',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'CLIN_Adult_Client_Information_Counselling_Information',
        'title' => E::ts('CLIN - Adult Client Information :: Counselling Information'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => [
          'name',
          'label',
          'description',
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Counselling_Information_OptionValue_Police',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Counselling_Information',
        'label' => E::ts('Police'),
        'value' => '1',
        'name' => 'Police',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Counselling_Information_OptionValue_Victim_Service_Unit',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Counselling_Information',
        'label' => E::ts('Victim Service Unit'),
        'value' => '2',
        'name' => 'Victim_Service_Unit',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Counselling_Information_OptionValue_Community_Organization',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Counselling_Information',
        'label' => E::ts('Community Organization'),
        'value' => '3',
        'name' => 'Community_Organization',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Counselling_Information_OptionValue_Hospital',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Counselling_Information',
        'label' => E::ts('Hospital'),
        'value' => '4',
        'name' => 'Hospital',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Counselling_Information_OptionValue_Government_Agency',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Counselling_Information',
        'label' => E::ts('Government Agency'),
        'value' => '5',
        'name' => 'Government_Agency',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Counselling_Information_OptionValue_Crown',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Counselling_Information',
        'label' => E::ts('Crown'),
        'value' => '6',
        'name' => 'Crown',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Counselling_Information_OptionValue_Self',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Counselling_Information',
        'label' => E::ts('Self'),
        'value' => '7',
        'name' => 'Self',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Counselling_Information_OptionValue_Friend_Family',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Counselling_Information',
        'label' => E::ts('Friend/Family'),
        'value' => '9',
        'name' => 'Friend_Family',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Counselling_Information_OptionValue_Professional_Private_Practition',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Counselling_Information',
        'label' => E::ts('Professional (Private Practitioner)'),
        'value' => '10',
        'name' => 'Professional_Private_Practition',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Counselling_Information_OptionValue_SIL',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Counselling_Information',
        'label' => E::ts('SIL'),
        'value' => '11',
        'name' => 'SIL',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Counselling_Information_OptionValue_Zebra',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Counselling_Information',
        'label' => E::ts('Zebra'),
        'value' => '12',
        'name' => 'Zebra',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Counselling_Information_OptionValue_Other',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Counselling_Information',
        'label' => E::ts('Other'),
        'value' => '8',
        'name' => 'Other',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_Adult_Information_CustomField_Counselling_Information',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_Adult_Information',
        'name' => 'Counselling_Information',
        'label' => E::ts('Counselling Information'),
        'html_type' => 'CheckBox',
        'help_pre' => E::ts('Referred by:'),
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'counselling_information_1325',
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Counselling_Information',
        'serialize' => 1,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_Adult_Information_CustomField_Other',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_Adult_Information',
        'name' => 'Other',
        'label' => E::ts('Other'),
        'html_type' => 'Text',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'other_1326',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_Adult_Information_CustomField_Availability',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_Adult_Information',
        'name' => 'Availability',
        'label' => E::ts('Availability'),
        'html_type' => 'Text',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'availability_1327',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_Adult_Information_CustomField_Current_Prior_counselling_experience_at_SACE',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_Adult_Information',
        'name' => 'Current_Prior_counselling_experience_at_SACE',
        'label' => E::ts('Current/Prior counselling experience at SACE'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'current_prior_counselling_experi_1328',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_Adult_Information_CustomField_Please_specify_name_of_therapist_indiv_family_group_year_s_or_f',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_Adult_Information',
        'name' => '_Please_specify_name_of_therapist_indiv_family_group_year_s_or_f',
        'label' => E::ts('(Please specify name of therapist, indiv/family/group, year(s) or frequency of sessions)'),
        'data_type' => 'Memo',
        'html_type' => 'TextArea',
        'attributes' => 'rows=4, cols=60',
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => '_please_specify_name_of_therapis_1329',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_Adult_Information_CustomField_Please_specify_name_of_therapist_indiv_family_group_year_s_or_fr',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_Adult_Information',
        'name' => 'Please_specify_name_of_therapist_indiv_family_group_year_s_or_fr',
        'label' => E::ts('Please specify name of therapist, indiv/family/group, year(s) or frequency of sessions at other)'),
        'data_type' => 'Memo',
        'html_type' => 'TextArea',
        'attributes' => 'rows=4, cols=60',
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'please_specify_name_of_therapist_1330',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_Adult_Information_CustomField_Current_Prior_counselling_experience_at_other',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_Adult_Information',
        'name' => 'Current_Prior_counselling_experience_at_other',
        'label' => E::ts('Current/Prior counselling experience at other'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'current_prior_counselling_experi_1331',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Is_your_reason_for_accessing_ou',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'CLIN_Adult_Client_Information_Is_your_reason_for_accessing_ou',
        'title' => E::ts('CLIN - Adult Client Information :: Is your reason for accessing our services to deal with: SA you experienced as a child or adolescent, SA you experienced as an adult, or both?'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => [
          'name',
          'label',
          'description',
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Is_your_reason_for_accessing_ou_OptionValue_SA_experienced_as_a_child_adole',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Is_your_reason_for_accessing_ou',
        'label' => E::ts('SA experienced as a child/adolescent'),
        'value' => '1',
        'name' => 'SA_experienced_as_a_child_adole',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Is_your_reason_for_accessing_ou_OptionValue_SA_experienced_as_an_adult',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Is_your_reason_for_accessing_ou',
        'label' => E::ts('SA experienced as an adult'),
        'value' => '2',
        'name' => 'SA_experienced_as_an_adult',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Is_your_reason_for_accessing_ou_OptionValue_Both',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Is_your_reason_for_accessing_ou',
        'label' => E::ts('Both'),
        'value' => '3',
        'name' => 'Both',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_Adult_Information_CustomField_Is_your_reason_for_accessing_our_services_to_deal_with_SA_you_ex',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_Adult_Information',
        'name' => 'Is_your_reason_for_accessing_our_services_to_deal_with_SA_you_ex',
        'label' => E::ts('Is your reason for accessing our services to deal with: SA you experienced as a child or adolescent, SA you experienced as an adult, or both?'),
        'html_type' => 'Select',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'is_your_reason_for_accessing_our_1334',
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Is_your_reason_for_accessing_ou',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Have_you_ever_had_a_history_of_',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'CLIN_Adult_Client_Information_Have_you_ever_had_a_history_of_',
        'title' => E::ts('CLIN - Adult Client Information :: Have you ever had a history of eating disorders?'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => [
          'name',
          'label',
          'description',
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Have_you_ever_had_a_history_of_OptionValue_Restricting',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Have_you_ever_had_a_history_of_',
        'label' => E::ts('Restricting'),
        'value' => '1',
        'name' => 'Restricting',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Have_you_ever_had_a_history_of_OptionValue_Binging',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Have_you_ever_had_a_history_of_',
        'label' => E::ts('Binging'),
        'value' => '2',
        'name' => 'Binging',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_Adult_Information_CustomField_Have_you_ever_had_a_history_of_eating_disorders_',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_Adult_Information',
        'name' => 'Have_you_ever_had_a_history_of_eating_disorders_',
        'label' => E::ts('Have you ever had a history of eating disorders?'),
        'html_type' => 'CheckBox',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'have_you_ever_had_a_history_of_e_1339',
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Have_you_ever_had_a_history_of_',
        'serialize' => 1,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_Adult_Information_CustomField_Is_this_currently_ongoing_or_in_the_past_',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_Adult_Information',
        'name' => 'Is_this_currently_ongoing_or_in_the_past_',
        'label' => E::ts('Is this currently ongoing or in the past?'),
        'data_type' => 'Memo',
        'html_type' => 'TextArea',
        'attributes' => 'rows=4, cols=60',
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'is_this_currently_ongoing_or_in__1340',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_Adult_Information_CustomField_Have_you_ever_had_any_mental_health_reasons_',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_Adult_Information',
        'name' => 'Have_you_ever_had_any_mental_health_reasons_',
        'label' => E::ts('Have you ever had any mental health diagnoses in your lifetime?'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'have_you_ever_had_any_mental_hea_1341',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_Adult_Information_CustomField_Specify_in_self_reporting_SR_or_diagnosed_Dx_and_by_whom_',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_Adult_Information',
        'name' => 'Specify_in_self_reporting_SR_or_diagnosed_Dx_and_by_whom_',
        'label' => E::ts('Specify if self-reporting (SR) or diagnosed (Dx) and by whom.'),
        'data_type' => 'Memo',
        'html_type' => 'TextArea',
        'attributes' => 'rows=4, cols=60',
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'specify_in_self_reporting_sr_or__1342',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_Adult_Information_CustomField_Are_you_currently_taking_any_medication_for_mental_health_reason',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_Adult_Information',
        'name' => 'Are_you_currently_taking_any_medication_for_mental_health_reason',
        'label' => E::ts('Are you currently taking any medication for mental health reasons?'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'are_you_currently_taking_any_med_1343',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_Adult_Information_CustomField_Details_name_dosage_reason_',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_Adult_Information',
        'name' => 'Details_name_dosage_reason_',
        'label' => E::ts('Details (name, dosage, reason)'),
        'data_type' => 'Memo',
        'html_type' => 'TextArea',
        'attributes' => 'rows=4, cols=60',
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'details_name_dosage_reason__1344',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_Adult_Information_CustomField_Are_you_currently_accessing_any_other_health_services_i_e_psychi',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_Adult_Information',
        'name' => 'Are_you_currently_accessing_any_other_health_services_i_e_psychi',
        'label' => E::ts('Are you currently accessing any other health services (i.e. psychiatrist, social worker, medical doctor, AHS?)'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'are_you_currently_accessing_any__1345',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_Adult_Information_CustomField_Details_name_organization_',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_Adult_Information',
        'name' => 'Details_name_organization_',
        'label' => E::ts('Details (name, organization)'),
        'data_type' => 'Memo',
        'html_type' => 'TextArea',
        'attributes' => 'rows=4, cols=60',
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'details_name_organization__1346',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_Adult_Information_CustomField_In_the_past_year_have_you_ever_been_hospitalized_due_to_mental_h',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_Adult_Information',
        'name' => 'In_the_past_year_have_you_ever_been_hospitalized_due_to_mental_h',
        'label' => E::ts('In the past year, have you ever been hospitalized due to mental health concerns?'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'in_the_past_year_have_you_ever_b_1347',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_Adult_Information_CustomField_Specify_dates_length_of_stay_reason_',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_Adult_Information',
        'name' => 'Specify_dates_length_of_stay_reason_',
        'label' => E::ts('Specify dates, length of stay, reason.'),
        'data_type' => 'Memo',
        'html_type' => 'TextArea',
        'attributes' => 'rows=4, cols=60',
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'specify_dates_length_of_stay_rea_1348',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_Adult_Information_CustomField_Do_you_have_any_health_concerns_you_would_like_your_counsellor_t',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_Adult_Information',
        'name' => 'Do_you_have_any_health_concerns_you_would_like_your_counsellor_t',
        'label' => E::ts('Do you have any health concerns you would like your counsellor to know about?'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'do_you_have_any_health_concerns__1349',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_Adult_Information_CustomField_Details_if_applicable',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_Adult_Information',
        'name' => 'Details_if_applicable',
        'label' => E::ts('Details if applicable'),
        'data_type' => 'Memo',
        'html_type' => 'TextArea',
        'attributes' => 'rows=4, cols=60',
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'details_if_applicable_1350',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Please_identify_if_you_have_a_h',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'CLIN_Adult_Client_Information_Please_identify_if_you_have_a_h',
        'title' => E::ts('CLIN - Adult Client Information :: Please identify if you have a history of substance use/addictions (i.e. drugs, alcohol, gambling, etc.).'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => [
          'name',
          'label',
          'description',
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Please_identify_if_you_have_a_h_OptionValue_No_history_of_use',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Please_identify_if_you_have_a_h',
        'label' => E::ts('No history of use'),
        'value' => '1',
        'name' => 'No_history_of_use',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Please_identify_if_you_have_a_h_OptionValue_Past_history_of_use',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Please_identify_if_you_have_a_h',
        'label' => E::ts('Past history of use'),
        'value' => '2',
        'name' => 'Past_history_of_use',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Please_identify_if_you_have_a_h_OptionValue_Active_use',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Please_identify_if_you_have_a_h',
        'label' => E::ts('Active use'),
        'value' => '3',
        'name' => 'Active_use',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_Adult_Information_CustomField_Please_identify_if_you_have_a_history_of_substance_use_addiction',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_Adult_Information',
        'name' => 'Please_identify_if_you_have_a_history_of_substance_use_addiction',
        'label' => E::ts('Please identify if you have a history of substance use/addictions (i.e. drugs, alcohol, gambling, etc.).'),
        'html_type' => 'Select',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'please_identify_if_you_have_a_hi_1356',
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Please_identify_if_you_have_a_h',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_Adult_Information_CustomField_If_active_please_specify_type_of_substance_behaviour_being_used_',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_Adult_Information',
        'name' => 'If_active_please_specify_type_of_substance_behaviour_being_used_',
        'label' => E::ts('Please specify type of substance/behaviour being used.'),
        'data_type' => 'Memo',
        'html_type' => 'TextArea',
        'attributes' => 'rows=4, cols=60',
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'if_active_please_specify_type_of_1353',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_Adult_Information_CustomField_If_active_what_supports_are_being_accessed_OR_what_referrals_wer',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_Adult_Information',
        'name' => 'If_active_what_supports_are_being_accessed_OR_what_referrals_wer',
        'label' => E::ts('What supports are being accessed?'),
        'data_type' => 'Memo',
        'html_type' => 'TextArea',
        'attributes' => 'rows=4, cols=60',
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'if_active_what_supports_are_bein_1355',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'title' => E::ts('CLIN - Adult Client Information :: Resources and referrals given:'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => [
          'name',
          'label',
          'description',
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_Private_counsellors',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('Private counsellors'),
        'value' => '1',
        'name' => 'Private_counsellors',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_Aboriginal_Counselling_Services',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('Aboriginal Counselling Services'),
        'value' => '2',
        'name' => 'Aboriginal_Counselling_Services',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_AHS',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('AHS'),
        'value' => '3',
        'name' => 'AHS',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_AISH',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('AISH'),
        'value' => '4',
        'name' => 'AISH',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_Bissell_Centre',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('Bissell Centre'),
        'value' => '5',
        'name' => 'Bissell_Centre',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_Catholic_Social_Services',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('Catholic Social Services'),
        'value' => '6',
        'name' => 'Catholic_Social_Services',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_City_of_Edmonton_Programs',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('City of Edmonton Programs'),
        'value' => '7',
        'name' => 'City_of_Edmonton_Programs',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_E4C_Housing',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('E4C Housing'),
        'value' => '8',
        'name' => 'E4C_Housing',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_Family_Centre',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('Family Centre'),
        'value' => '9',
        'name' => 'Family_Centre',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_Jewish_Family_Services',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('Jewish Family Services'),
        'value' => '10',
        'name' => 'Jewish_Family_Services',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_Native_Friendship_Centre',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('Native Friendship Centre'),
        'value' => '11',
        'name' => 'Native_Friendship_Centre',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_Psychiatrists',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('Psychiatrists'),
        'value' => '12',
        'name' => 'Psychiatrists',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_YWCA',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('YWCA'),
        'value' => '13',
        'name' => 'YWCA',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_SACE_PACS',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('SACE PACS'),
        'value' => '14',
        'name' => 'SACE_PACS',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_Action_for_Health_Communities',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('Action for Health Communities'),
        'value' => '15',
        'name' => 'Action_for_Health_Communities',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_AHS_24_7_Access',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('AHS - 24/7 Access'),
        'value' => '16',
        'name' => 'AHS_24_7_Access',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_Alberta_Works',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('Alberta Works'),
        'value' => '17',
        'name' => 'Alberta_Works',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_Boyle_Street',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('Boyle Street'),
        'value' => '18',
        'name' => 'Boyle_Street',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_CEASE',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('CEASE'),
        'value' => '19',
        'name' => 'CEASE',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_Community_Counselling_Centre',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('Community Counselling Centre'),
        'value' => '20',
        'name' => 'Community_Counselling_Centre',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_Elizabeth_Fry_ILA_Project',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('Elizabeth Fry - ILA Project'),
        'value' => '21',
        'name' => 'Elizabeth_Fry_ILA_Project',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_Family_doctors',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('Family doctors'),
        'value' => '22',
        'name' => 'Family_doctors',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_Metis_Child_and_Family_Services',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('Metis Child and Family Services'),
        'value' => '23',
        'name' => 'Metis_Child_and_Family_Services',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_Northgate',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('Northgate'),
        'value' => '24',
        'name' => 'Northgate',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_RCMP',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('RCMP'),
        'value' => '25',
        'name' => 'RCMP',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_Saffron_Centre',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('Saffron Centre'),
        'value' => '26',
        'name' => 'Saffron_Centre',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_Addictions_Counselling',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('Addictions Counselling'),
        'value' => '27',
        'name' => 'Addictions_Counselling',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_AHS_Addiction_Mental_Health_Ser',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('AHS - Addiction & Mental Health Services'),
        'value' => '28',
        'name' => 'AHS_Addiction_Mental_Health_Ser',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_Bent_Arrow',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('Bent Arrow'),
        'value' => '29',
        'name' => 'Bent_Arrow',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_CASA',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('CASA'),
        'value' => '30',
        'name' => 'CASA',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_Child_and_Family_Services',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('Child and Family Services'),
        'value' => '31',
        'name' => 'Child_and_Family_Services',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_Court_House',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('Court House'),
        'value' => '32',
        'name' => 'Court_House',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_Employment_Insurance',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('Employment Insurance'),
        'value' => '33',
        'name' => 'Employment_Insurance',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_Homeward_Trust',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('Homeward Trust'),
        'value' => '34',
        'name' => 'Homeward_Trust',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_Mustard_Seed',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('Mustard Seed'),
        'value' => '35',
        'name' => 'Mustard_Seed',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_Police_EPS_',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('Police (EPS)'),
        'value' => '36',
        'name' => 'Police_EPS_',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_Victim_Service_Units_VSUs_',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('Victim Service Units (VSUs)'),
        'value' => '37',
        'name' => 'Victim_Service_Units_VSUs_',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_Adult_Information_CustomField_Active_Substance_Use_Referrals',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_Adult_Information',
        'name' => 'Active_Substance_Use_Referrals',
        'label' => E::ts('What referrals were made?'),
        'html_type' => 'Autocomplete-Select',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'active_substance_use_referrals_1365',
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'serialize' => 1,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_Adult_Information_CustomField_Is_self_harming_behaviour_present_',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_Adult_Information',
        'name' => 'Is_self_harming_behaviour_present_',
        'label' => E::ts('Is self-harming behaviour present?'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'is_self_harming_behaviour_presen_1357',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_Adult_Information_CustomField_If_yes_specify_type_of_behaviour_frequency_etc_',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_Adult_Information',
        'name' => 'If_yes_specify_type_of_behaviour_frequency_etc_',
        'label' => E::ts('If yes, specify type of behaviour, frequency, etc.'),
        'data_type' => 'Memo',
        'html_type' => 'TextArea',
        'attributes' => 'rows=4, cols=60',
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'if_yes_specify_type_of_behaviour_1358',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_Adult_Information_CustomField_Have_you_experienced_any_thoughts_or_attempts_of_suicide_',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_Adult_Information',
        'name' => 'Have_you_experienced_any_thoughts_or_attempts_of_suicide_',
        'label' => E::ts('Have you experienced any thoughts or attempts of suicide?'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'have_you_experienced_any_thought_1359',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_Adult_Information_CustomField_If_yes_specify_date_of_last_attempt_s_and_if_there_is_a_present_',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_Adult_Information',
        'name' => 'If_yes_specify_date_of_last_attempt_s_and_if_there_is_a_present_',
        'label' => E::ts('If yes, specify date of last attempt(s) and if there is a present safety concern (yes or no).'),
        'data_type' => 'Memo',
        'html_type' => 'TextArea',
        'attributes' => 'rows=4, cols=60',
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'if_yes_specify_date_of_last_atte_1360',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_Adult_Information_CustomField_If_yes_resources_provided_e_g_crisis_line_distress_line_ER_famil',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_Adult_Information',
        'name' => 'If_yes_resources_provided_e_g_crisis_line_distress_line_ER_famil',
        'label' => E::ts('If yes, resources provided: (e.g. crisis line, distress line, ER, family doctor, CUSST)'),
        'data_type' => 'Memo',
        'html_type' => 'TextArea',
        'attributes' => 'rows=4, cols=60',
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'if_yes_resources_provided_e_g_cr_1361',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_Adult_Information_CustomField_Goals_identified_by_client_at_time_of_intake_or_any_requests_for',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_Adult_Information',
        'name' => 'Goals_identified_by_client_at_time_of_intake_or_any_requests_for',
        'label' => E::ts('Goals identified by client at time of intake or any requests for counselling:'),
        'data_type' => 'Memo',
        'html_type' => 'TextArea',
        'attributes' => 'rows=4, cols=60',
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'goals_identified_by_client_at_ti_1362',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_Adult_Information_CustomField_Resources_and_referrals_given_',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_Adult_Information',
        'name' => 'Resources_and_referrals_given_',
        'label' => E::ts('Resources and referrals given:'),
        'html_type' => 'CheckBox',
        'options_per_line' => 3,
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'resources_and_referrals_given__1363',
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'serialize' => 1,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Skills_for_Change',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'CLIN_Adult_Client_Information_Skills_for_Change',
        'title' => E::ts('CLIN - Adult Client Information :: Skills for Change'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => [
          'name',
          'label',
          'description',
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Skills_for_Change_OptionValue_Add_to_waiting_list',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Skills_for_Change',
        'label' => E::ts('Interested'),
        'value' => '1',
        'name' => 'Add_to_waiting_list',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_Adult_Information_CustomField_Skills_for_Change',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_Adult_Information',
        'name' => 'Skills_for_Change',
        'label' => E::ts('Skills for Change'),
        'html_type' => 'CheckBox',
        'is_active' => FALSE,
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'skills_for_change_1364',
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Skills_for_Change',
        'serialize' => 1,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_Adult_Information_CustomField_Would_you_be_comfortable_seeing_an_intern_counsellor_',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_Adult_Information',
        'name' => 'Would_you_be_comfortable_seeing_an_intern_counsellor_',
        'label' => E::ts('Would you be comfortable seeing an intern counsellor?'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'would_you_be_comfortable_seeing__1366',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_Adult_Information_CustomField_Would_you_be_comfortable_with_virtual_online_counselling_',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_Adult_Information',
        'name' => 'Would_you_be_comfortable_with_virtual_online_counselling_',
        'label' => E::ts('Would you be comfortable with virtual/online counselling?'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'would_you_be_comfortable_with_vi_1367',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_Adult_Information_CustomField_Clinicians_are_required_to_record_sessions_when_possible_for_fee',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_Adult_Information',
        'name' => 'Clinicians_are_required_to_record_sessions_when_possible_for_fee',
        'label' => E::ts('Clinicians are required to record sessions when possible for feedback from their supervisors, would you be comfortable with this?'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'clinicians_are_required_to_recor_1368',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_Adult_Information_CustomField_Provided_counselling_package_following_intake_',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_Adult_Information',
        'name' => 'Provided_counselling_package_following_intake_',
        'label' => E::ts('Provided counselling package following intake?'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'provided_counselling_package_fol_1369',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Discussed_receiving_up_to_15_se',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'CLIN_Adult_Client_Information_Discussed_receiving_up_to_15_se',
        'title' => E::ts('CLIN - Adult Client Information :: Discussed receiving up to 15 sessions and a brief psycho-ed around various factors that may impact the focus of the sessions. Factors may include substance use, coping behaviours, stabilization, concerns, etc.'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => [
          'name',
          'label',
          'description',
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Discussed_receiving_up_to_15_se_OptionValue_Yes',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Discussed_receiving_up_to_15_se',
        'label' => E::ts('Yes'),
        'value' => '1',
        'name' => 'Yes',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_Adult_Information_CustomField_Discussed_receiving_up_to_15_sessions_and_a_brief_psycho_ed_arou',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_Adult_Information',
        'name' => 'Discussed_receiving_up_to_15_sessions_and_a_brief_psycho_ed_arou',
        'label' => E::ts('Discussed receiving up to 15 sessions and a brief psycho-ed around various factors that may impact the focus of the sessions. Factors may include substance use, coping behaviours, stabilization, concerns'),
        'html_type' => 'CheckBox',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'discussed_receiving_up_to_15_ses_1378',
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Discussed_receiving_up_to_15_se',
        'serialize' => 1,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_Adult_Information_CustomField_Comfortability_with_diverse_backgrounds_of_counsellors',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_Adult_Information',
        'name' => 'Comfortability_with_diverse_backgrounds_of_counsellors',
        'label' => E::ts('Comfortability with diverse backgrounds of counsellors'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'comfortability_with_diverse_back_1371',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_Adult_Information_CustomField_Specify_client_s_comment',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_Adult_Information',
        'name' => 'Specify_client_s_comment',
        'label' => E::ts("Specify client's comment"),
        'data_type' => 'Memo',
        'html_type' => 'TextArea',
        'attributes' => 'rows=4, cols=60',
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'specify_client_s_comment_1372',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_Adult_Information_CustomField_Follow_up_for_counsellor',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_Adult_Information',
        'name' => 'Follow_up_for_counsellor',
        'label' => E::ts('Follow-up for counsellor'),
        'data_type' => 'Memo',
        'html_type' => 'TextArea',
        'attributes' => 'rows=4, cols=60',
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'follow_up_for_counsellor_1373',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_Adult_Information_CustomField_Counselling_in_other_language_requested_If_so_specify_which_',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_Adult_Information',
        'name' => 'Counselling_in_other_language_requested_If_so_specify_which_',
        'label' => E::ts('Counselling in other language requested? (If so, specify which).'),
        'html_type' => 'Text',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'counselling_in_other_language_re_1374',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Intake_Outcome',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'CLIN_Adult_Client_Information_Intake_Outcome',
        'title' => E::ts('CLIN - Adult Client Information :: Intake Outcome'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => [
          'name',
          'label',
          'description',
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Intake_Outcome_OptionValue_Emergency',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Intake_Outcome',
        'label' => E::ts('Emergency'),
        'value' => '1',
        'name' => 'Emergency',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Intake_Outcome_OptionValue_Crisis_Appointment',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Intake_Outcome',
        'label' => E::ts('Crisis Appointment'),
        'value' => '2',
        'name' => 'Crisis_Appointment',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Intake_Outcome_OptionValue_Individual_Counselling',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Intake_Outcome',
        'label' => E::ts('Individual Counselling'),
        'value' => '3',
        'name' => 'Individual_Counselling',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Intake_Outcome_OptionValue_Returning_Client',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Intake_Outcome',
        'label' => E::ts('Returning Client'),
        'value' => '4',
        'name' => 'Returning_Client',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Intake_Outcome_OptionValue_ASHA_interested_',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Intake_Outcome',
        'label' => E::ts('ASHA (interested)'),
        'value' => '5',
        'name' => 'ASHA_interested_',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Intake_Outcome_OptionValue_SASS_interested_',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Intake_Outcome',
        'label' => E::ts('SASS (interested)'),
        'value' => '6',
        'name' => 'SASS_interested_',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Intake_Outcome_OptionValue_Skills_for_Change_interested_',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Intake_Outcome',
        'label' => E::ts('Skills for Change (interested)'),
        'value' => '10',
        'name' => 'Skills_for_Change_interested_',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Intake_Outcome_OptionValue_Men_s_Group_interested_',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Intake_Outcome',
        'label' => E::ts("Men's Group (interested)"),
        'value' => '7',
        'name' => 'Men_s_Group_interested_',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Intake_Outcome_OptionValue_Court_Support',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Intake_Outcome',
        'label' => E::ts('Court Support'),
        'value' => '8',
        'name' => 'Court_Support',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Intake_Outcome_OptionValue_Not_appropriate_for_SACE_at_thi',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Intake_Outcome',
        'label' => E::ts('Not appropriate for SACE at this time'),
        'value' => '9',
        'name' => 'Not_appropriate_for_SACE_at_thi',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_Adult_Information_CustomField_Intake_Outcome',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_Adult_Information',
        'name' => 'Intake_Outcome',
        'label' => E::ts('Intake Outcome'),
        'html_type' => 'CheckBox',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'intake_outcome_1375',
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Intake_Outcome',
        'serialize' => 1,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_Adult_Information_CustomField_Estimated_wait_time',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_Adult_Information',
        'name' => 'Estimated_wait_time',
        'label' => E::ts('Estimated wait time'),
        'html_type' => 'Text',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'estimated_wait_time_1376',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_Adult_Information_CustomField_Do_you_have_an_accessibility_access_need_we_can_support_you_with',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_Adult_Information',
        'name' => 'Do_you_have_an_accessibility_access_need_we_can_support_you_with',
        'label' => E::ts('Do you have accessibility/access needs we can support you with for attending counselling?'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'do_you_have_an_accessibility_acc_1418',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_Adult_Information_CustomField_Accessibility_details_if_applicable',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_Adult_Information',
        'name' => 'Accessibility_details_if_applicable',
        'label' => E::ts('Accessibility details, if applicable'),
        'data_type' => 'Memo',
        'html_type' => 'TextArea',
        'attributes' => 'rows=4, cols=60',
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'accessibility_details_if_applica_1419',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_Adult_Information_CustomField_If_past_history_of_use_please_specify_type_of_substance_behaviou',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_Adult_Information',
        'name' => 'If_past_history_of_use_please_specify_type_of_substance_behaviou',
        'label' => E::ts('If past history of use, please specify type of substance/behaviour being used.'),
        'data_type' => 'Memo',
        'html_type' => 'TextArea',
        'attributes' => 'rows=4, cols=60',
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'if_past_history_of_use_please_sp_1431',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_Adult_Information_CustomField_Compliance_with_SACE_Policy',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_Adult_Information',
        'name' => 'Compliance_with_SACE_Policy',
        'label' => E::ts('Non-Compliance with SACE Policy'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'compliance_with_sace_policy_1432',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
    [
      'name' => 'CustomGroup_CLIN_Adult_Sexual_Assault_History',
      'entity' => 'CustomGroup',
      'cleanup' => 'unused',
      'update' => 'unmodified',
      'params' => [
        'version' => 4,
        'values' => [
          'name' => 'CLIN_Adult_Sexual_Assault_History',
          'title' => E::ts('CLIN - Adult Sexual Assault History'),
          'extends' => 'Individual',
          'extends_entity_column_value' => [
            'Client',
          ],
          'style' => 'Tab with table',
          'help_pre' => '',
          'help_post' => '',
          'weight' => 60,
          'is_multiple' => TRUE,
          'collapse_adv_display' => TRUE,
          'created_date' => '2024-05-10 09:53:40',
          'icon' => 'fa-plus',
        ],
        'match' => [
          'name',
        ],
      ],
    ],
    [
      'name' => 'CustomGroup_CLIN_Adult_Sexual_Assault_History_CustomField_Age_range_occured',
      'entity' => 'CustomField',
      'cleanup' => 'unused',
      'update' => 'unmodified',
      'params' => [
        'version' => 4,
        'values' => [
          'custom_group_id.name' => 'CLIN_Adult_Sexual_Assault_History',
          'name' => 'Age_range_occured',
          'label' => E::ts('Age (range) occured'),
          'data_type' => 'Memo',
          'html_type' => 'TextArea',
          'attributes' => 'rows=4, cols=60',
          'note_columns' => 60,
          'note_rows' => 4,
          'column_name' => 'age_range_occured_1335',
        ],
        'match' => [
          'name',
          'custom_group_id',
        ],
      ],
    ],
    [
      'name' => 'CustomGroup_CLIN_Adult_Sexual_Assault_History_CustomField_Medical_Attention_',
      'entity' => 'CustomField',
      'cleanup' => 'unused',
      'update' => 'unmodified',
      'params' => [
        'version' => 4,
        'values' => [
          'custom_group_id.name' => 'CLIN_Adult_Sexual_Assault_History',
          'name' => 'Medical_Attention_',
          'label' => E::ts('Medical Attention?'),
          'data_type' => 'Memo',
          'html_type' => 'TextArea',
          'attributes' => 'rows=4, cols=60',
          'note_columns' => 60,
          'note_rows' => 4,
          'column_name' => 'medical_attention__1336',
        ],
        'match' => [
          'name',
          'custom_group_id',
        ],
      ],
    ],
    [
      'name' => 'CustomGroup_CLIN_Adult_Sexual_Assault_History_CustomField_Police_Involvement_',
      'entity' => 'CustomField',
      'cleanup' => 'unused',
      'update' => 'unmodified',
      'params' => [
        'version' => 4,
        'values' => [
          'custom_group_id.name' => 'CLIN_Adult_Sexual_Assault_History',
          'name' => 'Police_Involvement_',
          'label' => E::ts('Police Involvement?'),
          'data_type' => 'Memo',
          'html_type' => 'TextArea',
          'attributes' => 'rows=4, cols=60',
          'note_columns' => 60,
          'note_rows' => 4,
          'column_name' => 'police_involvement__1337',
        ],
        'match' => [
          'name',
          'custom_group_id',
        ],
      ],
    ],
    [
      'name' => 'CustomGroup_CLIN_Adult_Sexual_Assault_History_CustomField_Relationship_to_Offender',
      'entity' => 'CustomField',
      'cleanup' => 'unused',
      'update' => 'unmodified',
      'params' => [
        'version' => 4,
        'values' => [
          'custom_group_id.name' => 'CLIN_Adult_Sexual_Assault_History',
          'name' => 'Relationship_to_Offender',
          'label' => E::ts('Relationship to Offender'),
          'data_type' => 'Memo',
          'html_type' => 'TextArea',
          'attributes' => 'rows=4, cols=60',
          'note_columns' => 60,
          'note_rows' => 4,
          'column_name' => 'relationship_to_offender_1338',
        ],
        'match' => [
          'name',
          'custom_group_id',
        ],
      ],
    ],
      [
        'name' => 'CustomGroup_Referral_Type',
        'entity' => 'CustomGroup',
        'cleanup' => 'unused',
        'update' => 'unmodified',
        'params' => [
          'version' => 4,
          'values' => [
            'name' => 'Referral_Type',
            'title' => E::ts('Referral Type'),
            'style' => 'Tab with table',
            'help_pre' => '',
            'help_post' => '',
            'weight' => 61,
            'is_multiple' => TRUE,
            'collapse_adv_display' => TRUE,
            'created_date' => '2024-05-10 12:04:31',
            'icon' => '',
          ],
          'match' => [
            'name',
          ],
        ],
      ],
      [
        'name' => 'OptionGroup_Referral_Type_Referral_Type',
        'entity' => 'OptionGroup',
        'cleanup' => 'unused',
        'update' => 'unmodified',
        'params' => [
          'version' => 4,
          'values' => [
            'name' => 'Referral_Type_Referral_Type',
            'title' => E::ts('Referral Type :: Referral Type'),
            'data_type' => 'String',
            'is_reserved' => FALSE,
            'option_value_fields' => [
              'name',
              'label',
              'description',
            ],
          ],
          'match' => [
            'name',
          ],
        ],
      ],
      [
        'name' => 'OptionGroup_Referral_Type_Referral_Type_OptionValue_Counselling_Agency',
        'entity' => 'OptionValue',
        'cleanup' => 'unused',
        'update' => 'unmodified',
        'params' => [
          'version' => 4,
          'values' => [
            'option_group_id.name' => 'Referral_Type_Referral_Type',
            'label' => E::ts('Counselling Agency'),
            'value' => '1',
            'name' => 'Counselling_Agency',
          ],
          'match' => [
            'option_group_id',
            'name',
            'value',
          ],
        ],
      ],
      [
        'name' => 'OptionGroup_Referral_Type_Referral_Type_OptionValue_Crisis_or_Support_and_Info_Line',
        'entity' => 'OptionValue',
        'cleanup' => 'unused',
        'update' => 'unmodified',
        'params' => [
          'version' => 4,
          'values' => [
            'option_group_id.name' => 'Referral_Type_Referral_Type',
            'label' => E::ts('Crisis or Support and Info Line (SIL)'),
            'value' => '2',
            'name' => 'Crisis_or_Support_and_Info_Line',
          ],
          'match' => [
            'option_group_id',
            'name',
            'value',
          ],
        ],
      ],
      [
        'name' => 'OptionGroup_Referral_Type_Referral_Type_OptionValue_Sexual_Assault_Center_SAC_',
        'entity' => 'OptionValue',
        'cleanup' => 'unused',
        'update' => 'unmodified',
        'params' => [
          'version' => 4,
          'values' => [
            'option_group_id.name' => 'Referral_Type_Referral_Type',
            'label' => E::ts('Sexual Assault Centre (SAC)'),
            'value' => '3',
            'name' => 'Sexual_Assault_Center_SAC_',
          ],
          'match' => [
            'option_group_id',
            'name',
            'value',
          ],
        ],
      ],
      [
        'name' => 'CustomGroup_Referral_Type_CustomField_Referral_Type',
        'entity' => 'CustomField',
        'cleanup' => 'unused',
        'update' => 'unmodified',
        'params' => [
          'version' => 4,
          'values' => [
            'custom_group_id.name' => 'Referral_Type',
            'name' => 'Referral_Type',
            'label' => E::ts('Referral Type'),
            'html_type' => 'CheckBox',
            'text_length' => 255,
            'note_columns' => 60,
            'note_rows' => 4,
            'column_name' => 'referral_type_1417',
            'option_group_id.name' => 'Referral_Type_Referral_Type',
            'serialize' => 1,
            'in_selector' => TRUE,
          ],
          'match' => [
            'name',
            'custom_group_id',
          ],
        ],
      ],
    ];
