<?php
return [
  [
    'name' => 'CustomGroup_Additional_Contact',
    'entity' => 'CustomGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Additional_Contact',
        'title' => E::ts('Additional Contact'),
        'extends' => 'Individual',
        'extends_entity_column_value' => [
          'Client',
        ],
        'style' => 'Tab with table',
        'collapse_display' => TRUE,
        'help_pre' => '',
        'help_post' => '',
        'weight' => 62,
        'is_multiple' => TRUE,
        'collapse_adv_display' => TRUE,
        'created_date' => '2024-06-20 16:18:04',
        'icon' => '',
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Additional_Contact_CustomField_Name',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Additional_Contact',
        'name' => 'Name',
        'label' => E::ts('Name'),
        'html_type' => 'Text',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'name_1433',
        'in_selector' => TRUE,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Additional_Contact_CustomField_Phone_Number',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Additional_Contact',
        'name' => 'Phone_Number',
        'label' => E::ts('Phone Number'),
        'html_type' => 'Text',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'phone_number_1434',
        'in_selector' => TRUE,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Additional_Contact_CustomField_Relationship',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Additional_Contact',
        'name' => 'Relationship',
        'label' => E::ts('Relationship'),
        'html_type' => 'Text',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'relationship_1435',
        'in_selector' => TRUE,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Additional_Contact_CustomField_Legal_Guardian_',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Additional_Contact',
        'name' => 'Legal_Guardian_',
        'label' => E::ts('Legal Guardian?'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'legal_guardian__1436',
        'in_selector' => TRUE,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
    [
      'name' => 'CustomGroup_CLIN_Adult_Intake_Activity_Data',
      'entity' => 'CustomGroup',
      'cleanup' => 'unused',
      'update' => 'unmodified',
      'params' => [
        'version' => 4,
        'values' => [
          'name' => 'CLIN_Adult_Intake_Activity_Data',
          'title' => E::ts('CLIN - Intake Activity Data'),
          'extends' => 'Activity',
          'style' => 'Inline',
          'help_pre' => '',
          'help_post' => '',
          'weight' => 58,
          'collapse_adv_display' => TRUE,
          'created_date' => '2024-05-10 07:12:24',
          'icon' => '',
        ],
        'match' => [
          'name',
        ],
      ],
    ],
    [
      'name' => 'CustomGroup_CLIN_Adult_Intake_Activity_Data_CustomField_Initial_Call',
      'entity' => 'CustomField',
      'cleanup' => 'unused',
      'update' => 'unmodified',
      'params' => [
        'version' => 4,
        'values' => [
          'custom_group_id.name' => 'CLIN_Adult_Intake_Activity_Data',
          'name' => 'Initial_Call',
          'label' => E::ts('Initial Call'),
          'data_type' => 'Date',
          'html_type' => 'Select Date',
          'text_length' => 255,
          'date_format' => 'yy-mm-dd',
          'time_format' => 2,
          'note_columns' => 60,
          'note_rows' => 4,
          'column_name' => 'initial_call_1413',
        ],
        'match' => [
          'name',
          'custom_group_id',
        ],
      ],
    ],
    [
      'name' => 'CustomGroup_CLIN_Adult_Intake_Activity_Data_CustomField_Intake_Completed',
      'entity' => 'CustomField',
      'cleanup' => 'unused',
      'update' => 'unmodified',
      'params' => [
        'version' => 4,
        'values' => [
          'custom_group_id.name' => 'CLIN_Adult_Intake_Activity_Data',
          'name' => 'Intake_Completed',
          'label' => E::ts('Intake Completed'),
          'data_type' => 'Date',
          'html_type' => 'Select Date',
          'text_length' => 255,
          'date_format' => 'yy-mm-dd',
          'time_format' => 2,
          'note_columns' => 60,
          'note_rows' => 4,
          'column_name' => 'intake_completed_1414',
        ],
        'match' => [
          'name',
          'custom_group_id',
        ],
      ],
    ],
    [
      'name' => 'CustomGroup_CLIN_Adult_Intake_Activity_Data_CustomField_Intake_Number',
      'entity' => 'CustomField',
      'cleanup' => 'unused',
      'update' => 'unmodified',
      'params' => [
        'version' => 4,
        'values' => [
          'custom_group_id.name' => 'CLIN_Adult_Intake_Activity_Data',
          'name' => 'Intake_Number',
          'label' => E::ts('Intake Number'),
          'html_type' => 'Text',
          'text_length' => 255,
          'note_columns' => 60,
          'note_rows' => 4,
          'column_name' => 'intake_number_1423',
        ],
        'match' => [
          'name',
          'custom_group_id',
        ],
      ],
    ],
      [
        'name' => 'CustomGroup_Case_Worker',
        'entity' => 'CustomGroup',
        'cleanup' => 'unused',
        'update' => 'unmodified',
        'params' => [
          'version' => 4,
          'values' => [
            'name' => 'Case_Worker',
            'title' => E::ts('Case Worker'),
            'extends' => 'Individual',
            'extends_entity_column_value' => [
              'Client',
            ],
            'style' => 'Inline',
            'help_pre' => '',
            'help_post' => '',
            'weight' => 17,
            'created_date' => '2021-08-18 12:48:54',
            'icon' => '',
          ],
          'match' => [
            'name',
          ],
        ],
      ],
      [
        'name' => 'CustomGroup_Case_Worker_CustomField_Name',
        'entity' => 'CustomField',
        'cleanup' => 'unused',
        'update' => 'unmodified',
        'params' => [
          'version' => 4,
          'values' => [
            'custom_group_id.name' => 'Case_Worker',
            'name' => 'Name',
            'label' => E::ts('Name'),
            'html_type' => 'Text',
            'text_length' => 255,
            'note_columns' => 60,
            'note_rows' => 4,
            'column_name' => 'name_175',
          ],
          'match' => [
            'name',
            'custom_group_id',
          ],
        ],
      ],
      [
        'name' => 'CustomGroup_Case_Worker_CustomField_Phone_Number',
        'entity' => 'CustomField',
        'cleanup' => 'unused',
        'update' => 'unmodified',
        'params' => [
          'version' => 4,
          'values' => [
            'custom_group_id.name' => 'Case_Worker',
            'name' => 'Phone_Number',
            'label' => E::ts('Phone Number'),
            'html_type' => 'Text',
            'text_length' => 255,
            'note_columns' => 60,
            'note_rows' => 4,
            'column_name' => 'phone_number_176',
          ],
          'match' => [
            'name',
            'custom_group_id',
          ],
        ],
      ],
      [
        'name' => 'OptionGroup_caller_20210924101842',
        'entity' => 'OptionGroup',
        'cleanup' => 'unused',
        'update' => 'unmodified',
        'params' => [
          'version' => 4,
          'values' => [
            'name' => 'caller_20210924101842',
            'title' => E::ts('Caller'),
            'data_type' => 'String',
            'is_reserved' => FALSE,
            'option_value_fields' => [
              'name',
              'label',
              'description',
            ],
          ],
          'match' => [
            'name',
          ],
        ],
      ],
      [
        'name' => 'OptionGroup_caller_20210924101842_OptionValue_Caller',
        'entity' => 'OptionValue',
        'cleanup' => 'unused',
        'update' => 'unmodified',
        'params' => [
          'version' => 4,
          'values' => [
            'option_group_id.name' => 'caller_20210924101842',
            'label' => E::ts('Caller'),
            'value' => '1',
            'name' => 'Caller',
          ],
          'match' => [
            'option_group_id',
            'name',
            'value',
          ],
        ],
      ],
      [
        'name' => 'CustomGroup_Case_Worker_CustomField_Caller',
        'entity' => 'CustomField',
        'cleanup' => 'unused',
        'update' => 'unmodified',
        'params' => [
          'version' => 4,
          'values' => [
            'custom_group_id.name' => 'Case_Worker',
            'name' => 'Caller',
            'label' => E::ts('Caller'),
            'html_type' => 'CheckBox',
            'is_searchable' => TRUE,
            'text_length' => 255,
            'note_columns' => 60,
            'note_rows' => 4,
            'column_name' => 'caller_301',
            'option_group_id.name' => 'caller_20210924101842',
            'serialize' => 1,
          ],
          'match' => [
            'name',
            'custom_group_id',
          ],
        ],
      ],
        [
          'name' => 'CustomGroup_Case_Worker',
          'entity' => 'CustomGroup',
          'cleanup' => 'unused',
          'update' => 'unmodified',
          'params' => [
            'version' => 4,
            'values' => [
              'name' => 'Case_Worker',
              'title' => E::ts('Case Worker'),
              'extends' => 'Individual',
              'extends_entity_column_value' => [
                'Client',
              ],
              'style' => 'Inline',
              'help_pre' => '',
              'help_post' => '',
              'weight' => 17,
              'created_date' => '2021-08-18 12:48:54',
              'icon' => '',
            ],
            'match' => [
              'name',
            ],
          ],
        ],
        [
          'name' => 'CustomGroup_Case_Worker_CustomField_Name',
          'entity' => 'CustomField',
          'cleanup' => 'unused',
          'update' => 'unmodified',
          'params' => [
            'version' => 4,
            'values' => [
              'custom_group_id.name' => 'Case_Worker',
              'name' => 'Name',
              'label' => E::ts('Name'),
              'html_type' => 'Text',
              'text_length' => 255,
              'note_columns' => 60,
              'note_rows' => 4,
              'column_name' => 'name_175',
            ],
            'match' => [
              'name',
              'custom_group_id',
            ],
          ],
        ],
        [
          'name' => 'CustomGroup_Case_Worker_CustomField_Phone_Number',
          'entity' => 'CustomField',
          'cleanup' => 'unused',
          'update' => 'unmodified',
          'params' => [
            'version' => 4,
            'values' => [
              'custom_group_id.name' => 'Case_Worker',
              'name' => 'Phone_Number',
              'label' => E::ts('Phone Number'),
              'html_type' => 'Text',
              'text_length' => 255,
              'note_columns' => 60,
              'note_rows' => 4,
              'column_name' => 'phone_number_176',
            ],
            'match' => [
              'name',
              'custom_group_id',
            ],
          ],
        ],
        [
          'name' => 'OptionGroup_caller_20210924101842',
          'entity' => 'OptionGroup',
          'cleanup' => 'unused',
          'update' => 'unmodified',
          'params' => [
            'version' => 4,
            'values' => [
              'name' => 'caller_20210924101842',
              'title' => E::ts('Caller'),
              'data_type' => 'String',
              'is_reserved' => FALSE,
              'option_value_fields' => [
                'name',
                'label',
                'description',
              ],
            ],
            'match' => [
              'name',
            ],
          ],
        ],
        [
          'name' => 'OptionGroup_caller_20210924101842_OptionValue_Caller',
          'entity' => 'OptionValue',
          'cleanup' => 'unused',
          'update' => 'unmodified',
          'params' => [
            'version' => 4,
            'values' => [
              'option_group_id.name' => 'caller_20210924101842',
              'label' => E::ts('Caller'),
              'value' => '1',
              'name' => 'Caller',
            ],
            'match' => [
              'option_group_id',
              'name',
              'value',
            ],
          ],
        ],
        [
          'name' => 'CustomGroup_Case_Worker_CustomField_Caller',
          'entity' => 'CustomField',
          'cleanup' => 'unused',
          'update' => 'unmodified',
          'params' => [
            'version' => 4,
            'values' => [
              'custom_group_id.name' => 'Case_Worker',
              'name' => 'Caller',
              'label' => E::ts('Caller'),
              'html_type' => 'CheckBox',
              'is_searchable' => TRUE,
              'text_length' => 255,
              'note_columns' => 60,
              'note_rows' => 4,
              'column_name' => 'caller_301',
              'option_group_id.name' => 'caller_20210924101842',
              'serialize' => 1,
            ],
            'match' => [
              'name',
              'custom_group_id',
            ],
          ],
        ],
          [
            'name' => 'CustomGroup_Legal_Guardian',
            'entity' => 'CustomGroup',
            'cleanup' => 'unused',
            'update' => 'unmodified',
            'params' => [
              'version' => 4,
              'values' => [
                'name' => 'Legal_Guardian',
                'title' => E::ts('Legal Guardian'),
                'extends' => 'Individual',
                'extends_entity_column_value' => [
                  'Client',
                ],
                'style' => 'Inline',
                'help_pre' => '',
                'help_post' => '',
                'weight' => 19,
                'created_date' => '2021-08-25 14:03:19',
                'icon' => '',
              ],
              'match' => [
                'name',
              ],
            ],
          ],
          [
            'name' => 'CustomGroup_Legal_Guardian_CustomField_Name',
            'entity' => 'CustomField',
            'cleanup' => 'unused',
            'update' => 'unmodified',
            'params' => [
              'version' => 4,
              'values' => [
                'custom_group_id.name' => 'Legal_Guardian',
                'name' => 'Name',
                'label' => E::ts('Name'),
                'html_type' => 'Text',
                'text_length' => 255,
                'note_columns' => 60,
                'note_rows' => 4,
                'column_name' => 'name_234',
              ],
              'match' => [
                'name',
                'custom_group_id',
              ],
            ],
          ],
          [
            'name' => 'CustomGroup_Legal_Guardian_CustomField_Phone_Number',
            'entity' => 'CustomField',
            'cleanup' => 'unused',
            'update' => 'unmodified',
            'params' => [
              'version' => 4,
              'values' => [
                'custom_group_id.name' => 'Legal_Guardian',
                'name' => 'Phone_Number',
                'label' => E::ts('Phone Number'),
                'html_type' => 'Text',
                'text_length' => 255,
                'note_columns' => 60,
                'note_rows' => 4,
                'column_name' => 'phone_number_235',
              ],
              'match' => [
                'name',
                'custom_group_id',
              ],
            ],
          ],
          [
            'name' => 'CustomGroup_Legal_Guardian_CustomField_Relationship',
            'entity' => 'CustomField',
            'cleanup' => 'unused',
            'update' => 'unmodified',
            'params' => [
              'version' => 4,
              'values' => [
                'custom_group_id.name' => 'Legal_Guardian',
                'name' => 'Relationship',
                'label' => E::ts('Relationship'),
                'html_type' => 'Text',
                'text_length' => 255,
                'note_columns' => 60,
                'note_rows' => 4,
                'column_name' => 'relationship_238',
              ],
              'match' => [
                'name',
                'custom_group_id',
              ],
            ],
          ],
          [
            'name' => 'OptionGroup_caller_20210924101842',
            'entity' => 'OptionGroup',
            'cleanup' => 'unused',
            'update' => 'unmodified',
            'params' => [
              'version' => 4,
              'values' => [
                'name' => 'caller_20210924101842',
                'title' => E::ts('Caller'),
                'data_type' => 'String',
                'is_reserved' => FALSE,
                'option_value_fields' => [
                  'name',
                  'label',
                  'description',
                ],
              ],
              'match' => [
                'name',
              ],
            ],
          ],
          [
            'name' => 'OptionGroup_caller_20210924101842_OptionValue_Caller',
            'entity' => 'OptionValue',
            'cleanup' => 'unused',
            'update' => 'unmodified',
            'params' => [
              'version' => 4,
              'values' => [
                'option_group_id.name' => 'caller_20210924101842',
                'label' => E::ts('Caller'),
                'value' => '1',
                'name' => 'Caller',
              ],
              'match' => [
                'option_group_id',
                'name',
                'value',
              ],
            ],
          ],
          [
            'name' => 'CustomGroup_Legal_Guardian_CustomField_Caller',
            'entity' => 'CustomField',
            'cleanup' => 'unused',
            'update' => 'unmodified',
            'params' => [
              'version' => 4,
              'values' => [
                'custom_group_id.name' => 'Legal_Guardian',
                'name' => 'Caller',
                'label' => E::ts('Caller'),
                'html_type' => 'CheckBox',
                'is_searchable' => TRUE,
                'text_length' => 255,
                'note_columns' => 60,
                'note_rows' => 4,
                'column_name' => 'caller_298',
                'option_group_id.name' => 'caller_20210924101842',
                'serialize' => 1,
              ],
              'match' => [
                'name',
                'custom_group_id',
              ],
            ],
          ],
            [
              'name' => 'CustomGroup_Family_Support_Worker',
              'entity' => 'CustomGroup',
              'cleanup' => 'unused',
              'update' => 'unmodified',
              'params' => [
                'version' => 4,
                'values' => [
                  'name' => 'Family_Support_Worker',
                  'title' => E::ts('Family Support Worker'),
                  'extends' => 'Individual',
                  'extends_entity_column_value' => [
                    'Client',
                  ],
                  'style' => 'Inline',
                  'help_pre' => '',
                  'help_post' => '',
                  'weight' => 20,
                  'created_date' => '2021-08-25 14:04:37',
                  'icon' => '',
                ],
                'match' => [
                  'name',
                ],
              ],
            ],
            [
              'name' => 'CustomGroup_Family_Support_Worker_CustomField_Name',
              'entity' => 'CustomField',
              'cleanup' => 'unused',
              'update' => 'unmodified',
              'params' => [
                'version' => 4,
                'values' => [
                  'custom_group_id.name' => 'Family_Support_Worker',
                  'name' => 'Name',
                  'label' => E::ts('Name'),
                  'html_type' => 'Text',
                  'text_length' => 255,
                  'note_columns' => 60,
                  'note_rows' => 4,
                  'column_name' => 'name_236',
                ],
                'match' => [
                  'name',
                  'custom_group_id',
                ],
              ],
            ],
            [
              'name' => 'CustomGroup_Family_Support_Worker_CustomField_Phone_Number',
              'entity' => 'CustomField',
              'cleanup' => 'unused',
              'update' => 'unmodified',
              'params' => [
                'version' => 4,
                'values' => [
                  'custom_group_id.name' => 'Family_Support_Worker',
                  'name' => 'Phone_Number',
                  'label' => E::ts('Phone Number'),
                  'html_type' => 'Text',
                  'text_length' => 255,
                  'note_columns' => 60,
                  'note_rows' => 4,
                  'column_name' => 'phone_number_237',
                ],
                'match' => [
                  'name',
                  'custom_group_id',
                ],
              ],
            ],
            [
              'name' => 'OptionGroup_caller_20210924101842',
              'entity' => 'OptionGroup',
              'cleanup' => 'unused',
              'update' => 'unmodified',
              'params' => [
                'version' => 4,
                'values' => [
                  'name' => 'caller_20210924101842',
                  'title' => E::ts('Caller'),
                  'data_type' => 'String',
                  'is_reserved' => FALSE,
                  'option_value_fields' => [
                    'name',
                    'label',
                    'description',
                  ],
                ],
                'match' => [
                  'name',
                ],
              ],
            ],
            [
              'name' => 'OptionGroup_caller_20210924101842_OptionValue_Caller',
              'entity' => 'OptionValue',
              'cleanup' => 'unused',
              'update' => 'unmodified',
              'params' => [
                'version' => 4,
                'values' => [
                  'option_group_id.name' => 'caller_20210924101842',
                  'label' => E::ts('Caller'),
                  'value' => '1',
                  'name' => 'Caller',
                ],
                'match' => [
                  'option_group_id',
                  'name',
                  'value',
                ],
              ],
            ],
            [
              'name' => 'CustomGroup_Family_Support_Worker_CustomField_Caller',
              'entity' => 'CustomField',
              'cleanup' => 'unused',
              'update' => 'unmodified',
              'params' => [
                'version' => 4,
                'values' => [
                  'custom_group_id.name' => 'Family_Support_Worker',
                  'name' => 'Caller',
                  'label' => E::ts('Caller'),
                  'html_type' => 'CheckBox',
                  'is_searchable' => TRUE,
                  'text_length' => 255,
                  'note_columns' => 60,
                  'note_rows' => 4,
                  'column_name' => 'caller_299',
                  'option_group_id.name' => 'caller_20210924101842',
                  'serialize' => 1,
                ],
                'match' => [
                  'name',
                  'custom_group_id',
                ],
              ],
            ],
              [
                'name' => 'CustomGroup_Legal_Guardian_Additional',
                'entity' => 'CustomGroup',
                'cleanup' => 'unused',
                'update' => 'unmodified',
                'params' => [
                  'version' => 4,
                  'values' => [
                    'name' => 'Legal_Guardian_Additional',
                    'title' => E::ts('Legal Guardian - Additional'),
                    'extends' => 'Individual',
                    'extends_entity_column_value' => [
                      'Client',
                    ],
                    'style' => 'Inline',
                    'help_pre' => '',
                    'help_post' => '',
                    'weight' => 21,
                    'created_date' => '2021-09-02 12:49:04',
                    'icon' => '',
                  ],
                  'match' => [
                    'name',
                  ],
                ],
              ],
              [
                'name' => 'CustomGroup_Legal_Guardian_Additional_CustomField_Name',
                'entity' => 'CustomField',
                'cleanup' => 'unused',
                'update' => 'unmodified',
                'params' => [
                  'version' => 4,
                  'values' => [
                    'custom_group_id.name' => 'Legal_Guardian_Additional',
                    'name' => 'Name',
                    'label' => E::ts('Name'),
                    'html_type' => 'Text',
                    'text_length' => 255,
                    'note_columns' => 60,
                    'note_rows' => 4,
                    'column_name' => 'name_242',
                  ],
                  'match' => [
                    'name',
                    'custom_group_id',
                  ],
                ],
              ],
              [
                'name' => 'CustomGroup_Legal_Guardian_Additional_CustomField_Phone_Number',
                'entity' => 'CustomField',
                'cleanup' => 'unused',
                'update' => 'unmodified',
                'params' => [
                  'version' => 4,
                  'values' => [
                    'custom_group_id.name' => 'Legal_Guardian_Additional',
                    'name' => 'Phone_Number',
                    'label' => E::ts('Phone Number'),
                    'html_type' => 'Text',
                    'text_length' => 255,
                    'note_columns' => 60,
                    'note_rows' => 4,
                    'column_name' => 'phone_number_243',
                  ],
                  'match' => [
                    'name',
                    'custom_group_id',
                  ],
                ],
              ],
              [
                'name' => 'CustomGroup_Legal_Guardian_Additional_CustomField_Relationship',
                'entity' => 'CustomField',
                'cleanup' => 'unused',
                'update' => 'unmodified',
                'params' => [
                  'version' => 4,
                  'values' => [
                    'custom_group_id.name' => 'Legal_Guardian_Additional',
                    'name' => 'Relationship',
                    'label' => E::ts('Relationship'),
                    'html_type' => 'Text',
                    'text_length' => 255,
                    'note_columns' => 60,
                    'note_rows' => 4,
                    'column_name' => 'relationship_244',
                  ],
                  'match' => [
                    'name',
                    'custom_group_id',
                  ],
                ],
              ],
              [
                'name' => 'OptionGroup_caller_20210924101842',
                'entity' => 'OptionGroup',
                'cleanup' => 'unused',
                'update' => 'unmodified',
                'params' => [
                  'version' => 4,
                  'values' => [
                    'name' => 'caller_20210924101842',
                    'title' => E::ts('Caller'),
                    'data_type' => 'String',
                    'is_reserved' => FALSE,
                    'option_value_fields' => [
                      'name',
                      'label',
                      'description',
                    ],
                  ],
                  'match' => [
                    'name',
                  ],
                ],
              ],
              [
                'name' => 'OptionGroup_caller_20210924101842_OptionValue_Caller',
                'entity' => 'OptionValue',
                'cleanup' => 'unused',
                'update' => 'unmodified',
                'params' => [
                  'version' => 4,
                  'values' => [
                    'option_group_id.name' => 'caller_20210924101842',
                    'label' => E::ts('Caller'),
                    'value' => '1',
                    'name' => 'Caller',
                  ],
                  'match' => [
                    'option_group_id',
                    'name',
                    'value',
                  ],
                ],
              ],
              [
                'name' => 'CustomGroup_Legal_Guardian_Additional_CustomField_Caller',
                'entity' => 'CustomField',
                'cleanup' => 'unused',
                'update' => 'unmodified',
                'params' => [
                  'version' => 4,
                  'values' => [
                    'custom_group_id.name' => 'Legal_Guardian_Additional',
                    'name' => 'Caller',
                    'label' => E::ts('Caller'),
                    'html_type' => 'CheckBox',
                    'is_searchable' => TRUE,
                    'text_length' => 255,
                    'note_columns' => 60,
                    'note_rows' => 4,
                    'column_name' => 'caller_300',
                    'option_group_id.name' => 'caller_20210924101842',
                    'serialize' => 1,
                  ],
                  'match' => [
                    'name',
                    'custom_group_id',
                  ],
                ],
              ],
              [
                'name' => 'CustomGroup_Legal_Guardian_Additional_CustomField_Legal_Guardian_',
                'entity' => 'CustomField',
                'cleanup' => 'unused',
                'update' => 'unmodified',
                'params' => [
                  'version' => 4,
                  'values' => [
                    'custom_group_id.name' => 'Legal_Guardian_Additional',
                    'name' => 'Legal_Guardian_',
                    'label' => E::ts('Legal Guardian?'),
                    'data_type' => 'Boolean',
                    'html_type' => 'Radio',
                    'text_length' => 255,
                    'note_columns' => 60,
                    'note_rows' => 4,
                    'column_name' => 'legal_guardian__1424',
                  ],
                  'match' => [
                    'name',
                    'custom_group_id',
                  ],
                ],
              ],
            ];