<?php

use CRM_Sacecustomfields_ExtensionUtil as E;

return [
  [
    'name' => 'CustomGroup_CLIN_C_and_Y_Information',
    'entity' => 'CustomGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'CLIN_C_and_Y_Information',
        'title' => E::ts('CLIN - C and Y Information'),
        'extends' => 'Individual',
        'extends_entity_column_value' => [
          'Client',
        ],
        'style' => 'Inline',
        'help_pre' => '',
        'help_post' => '',
        'weight' => 57,
        'collapse_adv_display' => TRUE,
        'created_date' => '2024-05-09 12:32:19',
        'icon' => '',
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_C_and_Y_Information_Verbal_informed_consent_achieved_',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'CLIN_C_and_Y_Information_Verbal_informed_consent_achieved_',
        'title' => E::ts('CLIN C and Y Information :: Verbal informed consent achieved?'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => [
          'name',
          'label',
          'description',
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_C_and_Y_Information_Verbal_informed_consent_achieved_OptionValue_Verbal_informed_consent_achieve',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_C_and_Y_Information_Verbal_informed_consent_achieved_',
        'label' => E::ts('Verbal informed consent achieved?'),
        'value' => '1',
        'name' => 'Verbal_informed_consent_achieve',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_C_and_Y_Information_CustomField_Verbal_informed_consent_achieved_',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_C_and_Y_Information',
        'name' => 'Verbal_informed_consent_achieved_',
        'label' => E::ts('Verbal informed consent achieved?'),
        'html_type' => 'CheckBox',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'verbal_informed_consent_achieved_1379',
        'option_group_id.name' => 'CLIN_C_and_Y_Information_Verbal_informed_consent_achieved_',
        'serialize' => 1,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_C_and_Y_Information_CustomField_Has_the_child_disclosed_an_experience_of_sexual_violence_',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_C_and_Y_Information',
        'name' => 'Has_the_child_disclosed_an_experience_of_sexual_violence_',
        'label' => E::ts('Has the child disclosed an experience of sexual violence?'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'has_the_child_disclosed_an_exper_1380',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_C_and_Y_Information_CustomField_To_whom_was_the_disclosure_made_',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_C_and_Y_Information',
        'name' => 'To_whom_was_the_disclosure_made_',
        'label' => E::ts('To whom was the disclosure made?'),
        'html_type' => 'Text',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'to_whom_was_the_disclosure_made__1381',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_C_and_Y_Information_CustomField_What_did_the_youth_disclose_to_you_about_the_abuse_assault_',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_C_and_Y_Information',
        'name' => 'What_did_the_youth_disclose_to_you_about_the_abuse_assault_',
        'label' => E::ts('What did the youth disclose to you about the abuse/assault?'),
        'data_type' => 'Memo',
        'html_type' => 'TextArea',
        'attributes' => 'rows=4, cols=60',
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'what_did_the_youth_disclose_to_y_1382',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_C_and_Y_Information_CustomField_Reported',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_C_and_Y_Information',
        'name' => 'Reported',
        'label' => E::ts('Reported'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'reported_1383',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_C_and_Y_Information_CustomField_If_NOT_reported_document_the_reporting_information_we_provided_t',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_C_and_Y_Information',
        'name' => 'If_NOT_reported_document_the_reporting_information_we_provided_t',
        'label' => E::ts('If NOT reported, document the reporting information we provided the caller:'),
        'data_type' => 'Memo',
        'html_type' => 'TextArea',
        'attributes' => 'rows=4, cols=60',
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'if_not_reported_document_the_rep_1384',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_C_and_Y_Information_CustomField_Child_youth_interviewed',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_C_and_Y_Information',
        'name' => 'Child_youth_interviewed',
        'label' => E::ts('Child/youth interviewed'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'child_youth_interviewed_1385',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_C_and_Y_Information_CustomField_If_child_youth_NOT_interviewed_why_',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_C_and_Y_Information',
        'name' => 'If_child_youth_NOT_interviewed_why_',
        'label' => E::ts('If child/youth NOT interviewed, why:'),
        'data_type' => 'Memo',
        'html_type' => 'TextArea',
        'attributes' => 'rows=4, cols=60',
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'if_child_youth_not_interviewed_w_1386',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_C_and_Y_Information_CustomField_Is_your_child_aware_you_are_arranging_counselling_services_for_t',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_C_and_Y_Information',
        'name' => 'Is_your_child_aware_you_are_arranging_counselling_services_for_t',
        'label' => E::ts('Is your child aware you are arranging counselling services for them?'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'is_your_child_aware_you_are_arra_1388',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_C_and_Y_Information_CustomField_Name_of_caller',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_C_and_Y_Information',
        'name' => 'Name_of_caller',
        'label' => E::ts('Name of caller'),
        'html_type' => 'Text',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'name_of_caller_1389',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_C_and_Y_Information_CustomField_Relationship_to_child_youth',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_C_and_Y_Information',
        'name' => 'Relationship_to_child_youth',
        'label' => E::ts('Relationship to child/youth'),
        'html_type' => 'Text',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'relationship_to_child_youth_1390',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_C_and_Y_Information_CustomField_Name_of_parent_s_guardian_s_',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_C_and_Y_Information',
        'name' => 'Name_of_parent_s_guardian_s_',
        'label' => E::ts('Name of parent(s)/guardian(s)'),
        'html_type' => 'Text',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'name_of_parent_s_guardian_s__1391',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_C_and_Y_Information_CustomField_Who_has_custody_of_the_child_youth_',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_C_and_Y_Information',
        'name' => 'Who_has_custody_of_the_child_youth_',
        'label' => E::ts('Who has custody of the child/youth?'),
        'data_type' => 'Memo',
        'html_type' => 'TextArea',
        'attributes' => 'rows=4, cols=60',
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'who_has_custody_of_the_child_you_1392',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Counselling_Information',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'CLIN_Adult_Client_Information_Counselling_Information',
        'title' => E::ts('CLIN - Adult Client Information :: Counselling Information'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => [
          'name',
          'label',
          'description',
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Counselling_Information_OptionValue_Police',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Counselling_Information',
        'label' => E::ts('Police'),
        'value' => '1',
        'name' => 'Police',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Counselling_Information_OptionValue_Victim_Service_Unit',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Counselling_Information',
        'label' => E::ts('Victim Service Unit'),
        'value' => '2',
        'name' => 'Victim_Service_Unit',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Counselling_Information_OptionValue_Community_Organization',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Counselling_Information',
        'label' => E::ts('Community Organization'),
        'value' => '3',
        'name' => 'Community_Organization',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Counselling_Information_OptionValue_Hospital',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Counselling_Information',
        'label' => E::ts('Hospital'),
        'value' => '4',
        'name' => 'Hospital',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Counselling_Information_OptionValue_Government_Agency',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Counselling_Information',
        'label' => E::ts('Government Agency'),
        'value' => '5',
        'name' => 'Government_Agency',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Counselling_Information_OptionValue_Crown',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Counselling_Information',
        'label' => E::ts('Crown'),
        'value' => '6',
        'name' => 'Crown',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Counselling_Information_OptionValue_Self',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Counselling_Information',
        'label' => E::ts('Self'),
        'value' => '7',
        'name' => 'Self',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Counselling_Information_OptionValue_Friend_Family',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Counselling_Information',
        'label' => E::ts('Friend/Family'),
        'value' => '9',
        'name' => 'Friend_Family',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Counselling_Information_OptionValue_Professional_Private_Practition',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Counselling_Information',
        'label' => E::ts('Professional (Private Practitioner)'),
        'value' => '10',
        'name' => 'Professional_Private_Practition',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Counselling_Information_OptionValue_SIL',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Counselling_Information',
        'label' => E::ts('SIL'),
        'value' => '11',
        'name' => 'SIL',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Counselling_Information_OptionValue_Zebra',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Counselling_Information',
        'label' => E::ts('Zebra'),
        'value' => '12',
        'name' => 'Zebra',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Counselling_Information_OptionValue_Other',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Counselling_Information',
        'label' => E::ts('Other'),
        'value' => '8',
        'name' => 'Other',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_C_and_Y_Information_CustomField_Referred_by',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_C_and_Y_Information',
        'name' => 'Referred_by',
        'label' => E::ts('Referred by'),
        'html_type' => 'CheckBox',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'referred_by_1393',
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Counselling_Information',
        'serialize' => 1,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_C_and_Y_Information_CustomField_If_referred_by_Other_please_type_in_referral_source_',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_C_and_Y_Information',
        'name' => 'If_referred_by_Other_please_type_in_referral_source_',
        'label' => E::ts('If referred by "Other", please type in referral source:'),
        'html_type' => 'Text',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'if_referred_by_other_please_type_1394',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_C_and_Y_Information_CustomField_Is_client_currently_accessing_counselling_services_',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_C_and_Y_Information',
        'name' => 'Is_client_currently_accessing_counselling_services_',
        'label' => E::ts('Is client currently accessing counselling services?'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'is_client_currently_accessing_co_1395',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_C_and_Y_Information_CustomField_Please_specify_name_of_therapist_and_frequency_of_sessions',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_C_and_Y_Information',
        'name' => 'Please_specify_name_of_therapist_and_frequency_of_sessions',
        'label' => E::ts('Please specify name of therapist and frequency of sessions'),
        'data_type' => 'Memo',
        'html_type' => 'TextArea',
        'attributes' => 'rows=4, cols=60',
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'please_specify_name_of_therapist_1396',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_C_and_Y_Information_CustomField_Has_client_received_counselling_at_SACE_before_',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_C_and_Y_Information',
        'name' => 'Has_client_received_counselling_at_SACE_before_',
        'label' => E::ts('Has client received counselling at SACE before?'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'has_client_received_counselling__1397',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_C_and_Y_Information_CustomField_If_yes_please_expand_',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_C_and_Y_Information',
        'name' => 'If_yes_please_expand_',
        'label' => E::ts('If yes, please expand:'),
        'data_type' => 'Memo',
        'html_type' => 'TextArea',
        'attributes' => 'rows=4, cols=60',
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'if_yes_please_expand__1398',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_C_and_Y_Information_CustomField_Are_there_any_concerns_your_counsellor_should_be_aware_of_such_a',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_C_and_Y_Information',
        'name' => 'Are_there_any_concerns_your_counsellor_should_be_aware_of_such_a',
        'label' => E::ts('Are there any concerns your counsellor should be aware of, such as current mental health diagnosis, mental health history, cognitive disabilities, mobility concerns, and any current safety concerns?'),
        'data_type' => 'Memo',
        'html_type' => 'TextArea',
        'attributes' => 'rows=4, cols=60',
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'are_there_any_concerns_your_coun_1399',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_C_and_Y_Information_CustomField_Current_medications',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_C_and_Y_Information',
        'name' => 'Current_medications',
        'label' => E::ts('Current medications'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'current_medications_1400',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_C_and_Y_Information_CustomField_If_yes_please_detail_medication_name_and_what_for_',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_C_and_Y_Information',
        'name' => 'If_yes_please_detail_medication_name_and_what_for_',
        'label' => E::ts('If yes, please detail medication name and what for:'),
        'data_type' => 'Memo',
        'html_type' => 'TextArea',
        'attributes' => 'rows=4, cols=60',
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'if_yes_please_detail_medication__1401',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_C_and_Y_Information_CustomField_Current_physician',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_C_and_Y_Information',
        'name' => 'Current_physician',
        'label' => E::ts('Current physician'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'current_physician_1402',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_C_and_Y_Information_CustomField_Name_City_1',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_C_and_Y_Information',
        'name' => 'Name_City_1',
        'label' => E::ts('Name & City 1'),
        'html_type' => 'Text',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'name_city_1_1403',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_C_and_Y_Information_CustomField_Current_psychiatrist',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_C_and_Y_Information',
        'name' => 'Current_psychiatrist',
        'label' => E::ts('Current psychiatrist'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'current_psychiatrist_1404',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_C_and_Y_Information_CustomField_Name_City_Psychiatrist',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_C_and_Y_Information',
        'name' => 'Name_City_Psychiatrist',
        'label' => E::ts('Name & City Psychiatrist'),
        'html_type' => 'Text',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'name_city_psychiatrist_1405',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'title' => E::ts('CLIN - Adult Client Information :: Resources and referrals given:'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => [
          'name',
          'label',
          'description',
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_Private_counsellors',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('Private counsellors'),
        'value' => '1',
        'name' => 'Private_counsellors',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_Aboriginal_Counselling_Services',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('Aboriginal Counselling Services'),
        'value' => '2',
        'name' => 'Aboriginal_Counselling_Services',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_AHS',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('AHS'),
        'value' => '3',
        'name' => 'AHS',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_AISH',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('AISH'),
        'value' => '4',
        'name' => 'AISH',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_Bissell_Centre',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('Bissell Centre'),
        'value' => '5',
        'name' => 'Bissell_Centre',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_Catholic_Social_Services',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('Catholic Social Services'),
        'value' => '6',
        'name' => 'Catholic_Social_Services',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_City_of_Edmonton_Programs',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('City of Edmonton Programs'),
        'value' => '7',
        'name' => 'City_of_Edmonton_Programs',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_E4C_Housing',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('E4C Housing'),
        'value' => '8',
        'name' => 'E4C_Housing',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_Family_Centre',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('Family Centre'),
        'value' => '9',
        'name' => 'Family_Centre',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_Jewish_Family_Services',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('Jewish Family Services'),
        'value' => '10',
        'name' => 'Jewish_Family_Services',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_Native_Friendship_Centre',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('Native Friendship Centre'),
        'value' => '11',
        'name' => 'Native_Friendship_Centre',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_Psychiatrists',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('Psychiatrists'),
        'value' => '12',
        'name' => 'Psychiatrists',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_YWCA',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('YWCA'),
        'value' => '13',
        'name' => 'YWCA',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_SACE_PACS',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('SACE PACS'),
        'value' => '14',
        'name' => 'SACE_PACS',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_Action_for_Health_Communities',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('Action for Health Communities'),
        'value' => '15',
        'name' => 'Action_for_Health_Communities',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_AHS_24_7_Access',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('AHS - 24/7 Access'),
        'value' => '16',
        'name' => 'AHS_24_7_Access',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_Alberta_Works',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('Alberta Works'),
        'value' => '17',
        'name' => 'Alberta_Works',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_Boyle_Street',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('Boyle Street'),
        'value' => '18',
        'name' => 'Boyle_Street',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_CEASE',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('CEASE'),
        'value' => '19',
        'name' => 'CEASE',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_Community_Counselling_Centre',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('Community Counselling Centre'),
        'value' => '20',
        'name' => 'Community_Counselling_Centre',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_Elizabeth_Fry_ILA_Project',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('Elizabeth Fry - ILA Project'),
        'value' => '21',
        'name' => 'Elizabeth_Fry_ILA_Project',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_Family_doctors',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('Family doctors'),
        'value' => '22',
        'name' => 'Family_doctors',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_Metis_Child_and_Family_Services',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('Metis Child and Family Services'),
        'value' => '23',
        'name' => 'Metis_Child_and_Family_Services',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_Northgate',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('Northgate'),
        'value' => '24',
        'name' => 'Northgate',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_RCMP',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('RCMP'),
        'value' => '25',
        'name' => 'RCMP',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_Saffron_Centre',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('Saffron Centre'),
        'value' => '26',
        'name' => 'Saffron_Centre',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_Addictions_Counselling',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('Addictions Counselling'),
        'value' => '27',
        'name' => 'Addictions_Counselling',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_AHS_Addiction_Mental_Health_Ser',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('AHS - Addiction & Mental Health Services'),
        'value' => '28',
        'name' => 'AHS_Addiction_Mental_Health_Ser',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_Bent_Arrow',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('Bent Arrow'),
        'value' => '29',
        'name' => 'Bent_Arrow',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_CASA',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('CASA'),
        'value' => '30',
        'name' => 'CASA',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_Child_and_Family_Services',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('Child and Family Services'),
        'value' => '31',
        'name' => 'Child_and_Family_Services',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_Court_House',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('Court House'),
        'value' => '32',
        'name' => 'Court_House',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_Employment_Insurance',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('Employment Insurance'),
        'value' => '33',
        'name' => 'Employment_Insurance',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_Homeward_Trust',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('Homeward Trust'),
        'value' => '34',
        'name' => 'Homeward_Trust',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_Mustard_Seed',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('Mustard Seed'),
        'value' => '35',
        'name' => 'Mustard_Seed',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_Police_EPS_',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('Police (EPS)'),
        'value' => '36',
        'name' => 'Police_EPS_',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_Adult_Client_Information_Resources_and_referrals_given_OptionValue_Victim_Service_Units_VSUs_',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'label' => E::ts('Victim Service Units (VSUs)'),
        'value' => '37',
        'name' => 'Victim_Service_Units_VSUs_',
        'description' => '',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_C_and_Y_Information_CustomField_Referrals_provided',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_C_and_Y_Information',
        'name' => 'Referrals_provided',
        'label' => E::ts('Referrals provided'),
        'html_type' => 'CheckBox',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'referrals_provided_1406',
        'option_group_id.name' => 'CLIN_Adult_Client_Information_Resources_and_referrals_given_',
        'serialize' => 1,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_C_and_Y_Information_CustomField_Waitlist_time_estimated',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_C_and_Y_Information',
        'name' => 'Waitlist_time_estimated',
        'label' => E::ts('Waitlist time estimated'),
        'data_type' => 'Memo',
        'html_type' => 'TextArea',
        'attributes' => 'rows=4, cols=60',
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'waitlist_time_estimated_1407',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_C_and_Y_Information_CustomField_For_clients_12_years_and_older_would_online_counselling_be_an_op',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_C_and_Y_Information',
        'name' => 'For_clients_12_years_and_older_would_online_counselling_be_an_op',
        'label' => E::ts('For clients 12 years and older, would online counselling be an option?'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'for_clients_12_years_and_older_w_1408',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_C_and_Y_Information_CustomField_Would_clients_be_comfortable_seeing_a_student_therapist_',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_C_and_Y_Information',
        'name' => 'Would_clients_be_comfortable_seeing_a_student_therapist_',
        'label' => E::ts('Would clients be comfortable seeing a student therapist?'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'would_clients_be_comfortable_see_1409',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_C_and_Y_Information_CustomField_Comfortability_with_diverse_backgrounds_of_counsellors',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_C_and_Y_Information',
        'name' => 'Comfortability_with_diverse_backgrounds_of_counsellors',
        'label' => E::ts('Comfortability with diverse backgrounds of counsellors'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'comfortability_with_diverse_back_1410',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_C_and_Y_Information_CustomField_If_yes_specify_client_s_comment_',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_C_and_Y_Information',
        'name' => 'If_yes_specify_client_s_comment_',
        'label' => E::ts("If yes, specify client's comment:"),
        'data_type' => 'Memo',
        'html_type' => 'TextArea',
        'attributes' => 'rows=4, cols=60',
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'if_yes_specify_client_s_comment__1411',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_C_and_Y_Information_Discussed_receiving_up_to_15_session',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'CLIN_C_and_Y_Information_Discussed_receiving_up_to_15_session',
        'title' => E::ts('CLIN C and Y Information :: Discussed receiving up to 15 sessions and a brief psycho-ed around various factors that may impact the focus of the sessions. Factors may include substance use, coping behaviours, stabilization, concerns, etc.'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => [
          'name',
          'label',
          'description',
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_C_and_Y_Information_Discussed_receiving_up_to_15_session_OptionValue_Yes',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_C_and_Y_Information_Discussed_receiving_up_to_15_session',
        'label' => E::ts('Yes'),
        'value' => '1',
        'name' => 'Yes',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_C_and_Y_Information_CustomField_Discussed_receiving_up_to_15_sessions_and_a_brief_psycho_ed_arou',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_C_and_Y_Information',
        'name' => 'Discussed_receiving_up_to_15_sessions_and_a_brief_psycho_ed_arou',
        'label' => E::ts('Discussed receiving up to 15 sessions and a brief psycho-ed around various factors that may impact the focus of the sessions. Factors may include substance use, coping behaviours, stabilization, concerns, etc.'),
        'html_type' => 'CheckBox',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'discussed_receiving_up_to_15_ses_1412',
        'option_group_id.name' => 'CLIN_C_and_Y_Information_Discussed_receiving_up_to_15_session',
        'serialize' => 1,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_C_and_Y_Information_Gender_of_Child_Youth',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'CLIN_C_and_Y_Information_Gender_of_Child_Youth',
        'title' => E::ts('CLIN - C and Y Information :: Gender of Child/Youth'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => [
          'name',
          'label',
          'description',
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_C_and_Y_Information_Gender_of_Child_Youth_OptionValue_Male',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_C_and_Y_Information_Gender_of_Child_Youth',
        'label' => E::ts('Male'),
        'value' => 'male',
        'name' => 'Male',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_C_and_Y_Information_Gender_of_Child_Youth_OptionValue_Female',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_C_and_Y_Information_Gender_of_Child_Youth',
        'label' => E::ts('Female'),
        'value' => 'female',
        'name' => 'Female',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_C_and_Y_Information_Gender_of_Child_Youth_OptionValue_Transgender',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_C_and_Y_Information_Gender_of_Child_Youth',
        'label' => E::ts('Transgender'),
        'value' => 'transgender',
        'name' => 'Transgender',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_CLIN_C_and_Y_Information_Gender_of_Child_Youth_OptionValue_Prefer_not_to_say',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'CLIN_C_and_Y_Information_Gender_of_Child_Youth',
        'label' => E::ts('Prefer not to say'),
        'value' => 'prefer not to say',
        'name' => 'Prefer_not_to_say',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_C_and_Y_Information_CustomField_Gender_of_Child_Youth',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_C_and_Y_Information',
        'name' => 'Gender_of_Child_Youth',
        'label' => E::ts('Gender of Child/Youth'),
        'html_type' => 'Radio',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'gender_of_child_youth_1420',
        'option_group_id.name' => 'CLIN_C_and_Y_Information_Gender_of_Child_Youth',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_C_and_Y_Information_CustomField_Date_of_Birth',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_C_and_Y_Information',
        'name' => 'Date_of_Birth',
        'label' => E::ts('Date of Birth'),
        'data_type' => 'Date',
        'html_type' => 'Select Date',
        'text_length' => 255,
        'date_format' => 'yy-mm-dd',
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'date_of_birth_1421',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_C_and_Y_Information_CustomField_AHS_',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_C_and_Y_Information',
        'name' => 'AHS_',
        'label' => E::ts('AHS #'),
        'html_type' => 'Text',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'ahs__1422',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_C_and_Y_Information_CustomField_Are_there_any_current_unresolved_custody_or_access_matters_invol',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_C_and_Y_Information',
        'name' => 'Are_there_any_current_unresolved_custody_or_access_matters_invol',
        'label' => E::ts('Are there any current unresolved custody or access matters involving the child?'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'are_there_any_current_unresolved_1429',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_CLIN_C_and_Y_Information_CustomField_Information_on_custody_or_access_matters_',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'CLIN_C_and_Y_Information',
        'name' => 'Information_on_custody_or_access_matters_',
        'label' => E::ts('Information on custody or access matters:'),
        'data_type' => 'Memo',
        'html_type' => 'TextArea',
        'attributes' => 'rows=4, cols=60',
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'information_on_custody_or_access_1430',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
];
