<?php

use DateTime as GlobalDateTime;
use Drupal\webform\Utility\WebformFormHelper;
use \Drupal\Core\Datetime\DrupalDateTime;
use Drupal\Core\Datetime\Element\Datetime;

require_once 'ped_online_course_booking_update.variables.php';

/**
 * Implements hook_form_alter().
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 */
function ped_online_course_booking_update_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if($form_id == "webform_submission_ped_online_course_booking_update_add_form"){    
    //attach js
    $form['#attached']['library'][] = 'ped_online_course_booking_update/ped_online_course_booking_update';
    $form['#attached']['drupalSettings']['ped_online_course_booking_update']['start_date'] = '#edit-' . str_replace('_', '-', PED_ONLINE_COURSE_BOOKING_UPDATE_START_DATE);
    $form['#attached']['drupalSettings']['ped_online_course_booking_update']['end_date'] = '#edit-' . str_replace('_', '-', PED_ONLINE_COURSE_BOOKING_UPDATE_END_DATE);
    // $form['#attached']['drupalSettings']['ped_online_course_booking_update']['optional_addons_select'] = $constants['optional_addons_select'];
    // $form['#attached']['drupalSettings']['ped_online_course_booking_update']['high_school_checkbox'] = $constants['high_school_checkbox'];
    
    //Get webform elements
    $elements = WebformFormHelper::flattenElements($form);
    if (empty($elements)) {
      return;
    }
    \Drupal::service('civicrm')->initialize();
    //Activity ID
    $aid = \Drupal::request()->query->get('aid') ?? 0;
    if (empty($aid) || !is_numeric($aid)) {
      return;
    }

    //End Date
    $activity = \Civi\Api4\Activity::get(FALSE)
    ->addSelect('Booking_Information.End_Date')
    ->addWhere('id', '=', $aid)
    ->setLimit(1)
    ->execute();
    $end_date = $activity->first()['Booking_Information.End_Date'];
    if($end_date) {
      // $elements[PED_ONLINE_COURSE_BOOKING_UPDATE_END_DATE]['#default_value'] =  date_create_from_format('YmdH',$end_date)->format('Y-m-d');
    }

    if (empty($elements[PED_ONLINE_COURSE_BOOKING_UPDATE_FACILITATING_PROGRAM]['#default_value'])) {
      $elements[PED_ONLINE_COURSE_BOOKING_UPDATE_FACILITATING_PROGRAM]['#default_value'] = 'PublicEducation';
    }

$bt = $elements['civicrm_1_activity_1_activity_activity_type_id']['#default_value'];
    if ($bt == PED_ONLINE_COURSE_BOOKING_UPDATE_ADULT_ACTIVITY) {
      $elements[PED_ONLINE_COURSE_BOOKING_UPDATE_ONLINE_COURSES]['#options'] = array_intersect($elements[PED_ONLINE_COURSE_BOOKING_UPDATE_ONLINE_COURSES]['#options'], [
        'Information for Partners & Supporters' => 'Information for Partners & Supporters',
        'Recognizing & Responding to Sexual Violence' => 'Recognizing & Responding to Sexual Violence',
        'Racism & Sexual Violence' => 'Racism & Sexual Violence',
        'Sexual Violence & the 2SLGBTQ+ Community' => 'Sexual Violence & the 2SLGBTQ+ Community',
      ]);      
    }
    elseif ($bt == PED_ONLINE_COURSE_BOOKING_UPDATE_YOUTH_ACTIVITY) {
      $elements[PED_ONLINE_COURSE_BOOKING_UPDATE_ONLINE_COURSES]['#options'] = array_intersect($elements[PED_ONLINE_COURSE_BOOKING_UPDATE_ONLINE_COURSES]['#options'], [
        'Ask First: Sexual Harassment ' => 'Ask First: Sexual Harassment',
        'Ask First: Sexual Assault & Consent ' => 'Ask First: Sexual Assault & Consent',
        'Ask First: Non-Consensual Photo Sharing ' => 'Ask First: Non-Consensual Photo Sharing',
        'Consent: Ask Me About It!' => 'Consent: Ask Me About It!',
      ]);
    }
  }
}

function ped_online_course_booking_update_preprocess_page_title(&$variables, $hook) {
  //Activity ID
  $aid = \Drupal::request()->query->get('aid') ?? 0;
  if (empty($aid) || !is_numeric($aid)) {
    return;
  }

  \Drupal::service('civicrm')->initialize();
  //Get booking type from activity
  $activity = \Civi\Api4\Activity::get(FALSE)
  ->addSelect('activity_type_id')
  ->addWhere('id', '=', $aid)
  ->setLimit(1)
  ->execute();
  $bt = $activity->first()['activity_type_id'];

  $current_path = \Drupal::service('path.current')->getPath();

  if($current_path == '/webform/ped_online_course_booking_update') {
    if($bt == PED_ONLINE_COURSE_BOOKING_UPDATE_YOUTH_ACTIVITY) {
      $variables['title'] = [
        '#markup' => 'Youth Online Course Booking Update',
      ];
    }
    elseif($bt == PED_ONLINE_COURSE_BOOKING_UPDATE_ADULT_ACTIVITY) {
      $variables['title'] = [
        '#markup' => 'Adult Online Course Booking Update',
      ];
    }
  }
}
