<?php
return [
  'OptionGroup_activity_type_OptionValue_Client Assessment Required' => [
    'name' => 'OptionGroup_activity_type_OptionValue_Client Assessment Required', 
    'entity' => 'OptionValue', 
    'cleanup' => 'unused', 
    'update' => 'unmodified', 
    'params' => [
      'version' => 4, 
      'values' => [
        'option_group_id.name' => 'activity_type', 
        'label' => 'Client Assessment Required', 
        'value' => '180', 
        'name' => 'Client Assessment Required', 
        'grouping' => NULL, 
        'filter' => 0, 
        'is_default' => FALSE, 
        'weight' => 180, 
        'description' => NULL, 
        'is_optgroup' => FALSE, 
        'is_reserved' => TRUE, 
        'is_active' => TRUE, 
        'component_id' => NULL, 
        'domain_id' => NULL, 
        'visibility_id' => NULL, 
        'icon' => NULL, 
        'color' => NULL,
      ], 
      'match' => [
        'option_group_id',
        'name',
      ],
    ],
  ],
  'OptionGroup_activity_type_OptionValue_Update File Data' => [
    'name' => 'OptionGroup_activity_type_OptionValue_Update File Data', 
    'entity' => 'OptionValue', 
    'cleanup' => 'unused', 
    'update' => 'unmodified', 
    'params' => [
      'version' => 4, 
      'values' => [
        'option_group_id.name' => 'activity_type', 
        'label' => 'Update File Data', 
        'value' => '181', 
        'name' => 'Update File Data', 
        'grouping' => NULL, 
        'filter' => 0, 
        'is_default' => FALSE, 
        'weight' => 181, 
        'description' => NULL, 
        'is_optgroup' => FALSE, 
        'is_reserved' => TRUE, 
        'is_active' => TRUE, 
        'component_id' => NULL, 
        'domain_id' => NULL, 
        'visibility_id' => NULL, 
        'icon' => NULL, 
        'color' => NULL,
      ], 
      'match' => [
        'option_group_id',
        'name',
      ],
    ],
  ],
  'OptionGroup_activity_type_OptionValue_Booking' => [
    'name' => 'OptionGroup_activity_type_OptionValue_Booking', 
    'entity' => 'OptionValue', 
    'cleanup' => 'unused', 
    'update' => 'unmodified', 
    'params' => [
      'version' => 4, 
      'values' => [
        'option_group_id.name' => 'activity_type', 
        'label' => 'Booking', 
        'value' => '182', 
        'name' => 'Booking',
        'grouping' => NULL, 
        'filter' => 0, 
        'is_default' => FALSE, 
        'weight' => 182, 
        'description' => NULL, 
        'is_optgroup' => FALSE, 
        'is_reserved' => TRUE, 
        'is_active' => TRUE, 
        'component_id' => NULL, 
        'domain_id' => NULL, 
        'visibility_id' => NULL, 
        'icon' => NULL, 
        'color' => NULL,
      ], 
      'match' => [
        'option_group_id',
        'name',
      ],
    ],
  ],
  'OptionGroup_activity_type_OptionValue_Playroom' => [
    'name' => 'OptionGroup_activity_type_OptionValue_Playroom', 
    'entity' => 'OptionValue', 
    'cleanup' => 'unused', 
    'update' => 'unmodified', 
    'params' => [
      'version' => 4, 
      'values' => [
        'option_group_id.name' => 'activity_type', 
        'label' => 'Playroom', 
        'value' => '183', 
        'name' => 'Playroom', 
        'grouping' => NULL, 
        'filter' => 0, 
        'is_default' => FALSE, 
        'weight' => 183, 
        'description' => NULL, 
        'is_optgroup' => FALSE, 
        'is_reserved' => TRUE, 
        'is_active' => TRUE, 
        'component_id' => NULL, 
        'domain_id' => NULL, 
        'visibility_id' => NULL, 
        'icon' => NULL, 
        'color' => NULL,
      ], 
      'match' => [
        'option_group_id',
        'name',
      ],
    ],
  ],
  'OptionGroup_activity_type_OptionValue_Privacy Concern' => [
    'name' => 'OptionGroup_activity_type_OptionValue_Privacy Concern', 
    'entity' => 'OptionValue', 
    'cleanup' => 'unused', 
    'update' => 'unmodified', 
    'params' => [
      'version' => 4, 
      'values' => [
        'option_group_id.name' => 'activity_type', 
        'label' => 'Privacy Concern', 
        'value' => '184', 
        'name' => 'Privacy Concern', 
        'grouping' => NULL, 
        'filter' => 0, 
        'is_default' => FALSE, 
        'weight' => 184, 
        'description' => NULL, 
        'is_optgroup' => FALSE, 
        'is_reserved' => TRUE, 
        'is_active' => TRUE, 
        'component_id' => NULL, 
        'domain_id' => NULL, 
        'visibility_id' => NULL, 
        'icon' => NULL, 
        'color' => NULL,
      ], 
      'match' => [
        'option_group_id',
        'name',
      ],
    ],
  ],
];
