<?php
return [
  'OptionValue_Client Assessment Required' => [
    'name' => 'OptionValue_Client Assessment Required', 
    'entity' => 'OptionValue', 
    'cleanup' => 'unused', 
    'update' => 'unmodified', 
    'params' => [
      'version' => 4, 
      'values' => [
        'option_group_id.name' => 'activity_type', 
        'label' => 'Client Assessment Required', 
        'value' => '180', 
        'name' => 'client_assessment_required', 
        'grouping' => NULL, 
        'filter' => 0, 
        'is_default' => FALSE, 
        'weight' => 1, 
        'description' => NULL, 
        'is_optgroup' => FALSE, 
        'is_reserved' => TRUE, 
        'is_active' => TRUE, 
        'component_id' => NULL, 
        'domain_id' => NULL, 
        'visibility_id' => NULL, 
        'icon' => NULL, 
        'color' => NULL,
      ], 
      'match' => [
        'name',
      ],
    ],
  ],
  'OptionValue_Update File Data' => [
    'name' => 'OptionValue_Client Assessment Required', 
    'entity' => 'OptionValue', 
    'cleanup' => 'unused', 
    'update' => 'unmodified', 
    'params' => [
      'version' => 4, 
      'values' => [
        'option_group_id.name' => 'activity_type', 
        'label' => 'Update File Data', 
        'value' => '181', 
        'name' => 'update_file_data', 
        'grouping' => NULL, 
        'filter' => 0, 
        'is_default' => FALSE, 
        'weight' => 1, 
        'description' => NULL, 
        'is_optgroup' => FALSE, 
        'is_reserved' => TRUE, 
        'is_active' => TRUE, 
        'component_id' => NULL, 
        'domain_id' => NULL, 
        'visibility_id' => NULL, 
        'icon' => NULL, 
        'color' => NULL,
      ], 
      'match' => [
        'name',
      ],
    ],
  ],
  'OptionValue_Booking' => [
    'name' => 'OptionValue_Booking', 
    'entity' => 'OptionValue', 
    'cleanup' => 'unused', 
    'update' => 'unmodified', 
    'params' => [
      'version' => 4, 
      'values' => [
        'option_group_id.name' => 'activity_type', 
        'label' => 'Booking', 
        'value' => '182', 
        'name' => 'booking', 
        'grouping' => NULL, 
        'filter' => 0, 
        'is_default' => FALSE, 
        'weight' => 1, 
        'description' => NULL, 
        'is_optgroup' => FALSE, 
        'is_reserved' => TRUE, 
        'is_active' => TRUE, 
        'component_id' => NULL, 
        'domain_id' => NULL, 
        'visibility_id' => NULL, 
        'icon' => NULL, 
        'color' => NULL,
      ], 
      'match' => [
        'name',
      ],
    ],
  ],
  'OptionValue_Playroom' => [
    'name' => 'OptionValue_Playroom', 
    'entity' => 'OptionValue', 
    'cleanup' => 'unused', 
    'update' => 'unmodified', 
    'params' => [
      'version' => 4, 
      'values' => [
        'option_group_id.name' => 'activity_type', 
        'label' => 'Playroom', 
        'value' => '183', 
        'name' => 'playroom', 
        'grouping' => NULL, 
        'filter' => 0, 
        'is_default' => FALSE, 
        'weight' => 1, 
        'description' => NULL, 
        'is_optgroup' => FALSE, 
        'is_reserved' => TRUE, 
        'is_active' => TRUE, 
        'component_id' => NULL, 
        'domain_id' => NULL, 
        'visibility_id' => NULL, 
        'icon' => NULL, 
        'color' => NULL,
      ], 
      'match' => [
        'name',
      ],
    ],
  ],
  'OptionValue_Privacy Concern' => [
    'name' => 'OptionValue_Client Assessment Required', 
    'entity' => 'OptionValue', 
    'cleanup' => 'unused', 
    'update' => 'unmodified', 
    'params' => [
      'version' => 4, 
      'values' => [
        'option_group_id.name' => 'activity_type', 
        'label' => 'Privacy Concern', 
        'value' => '184', 
        'name' => 'privacy_concern', 
        'grouping' => NULL, 
        'filter' => 0, 
        'is_default' => FALSE, 
        'weight' => 1, 
        'description' => NULL, 
        'is_optgroup' => FALSE, 
        'is_reserved' => TRUE, 
        'is_active' => TRUE, 
        'component_id' => NULL, 
        'domain_id' => NULL, 
        'visibility_id' => NULL, 
        'icon' => NULL, 
        'color' => NULL,
      ], 
      'match' => [
        'name',
      ],
    ],
  ],
];
