<?php

use Drupal\views\ViewExecutable;
use Drupal\views\Plugin\views\query\QueryPluginBase;

/**
 * Implements hook_civicrm_alter_drupal_entities
 */
function clin_waitlist_civicrm_alter_drupal_entities(&$civicrm_entity_info) {
  $civicrm_entity_info['civicrm_subscription_history'] = [
    'civicrm entity label' => ts('SubscriptionHistory'),
    'civicrm entity name' => 'subscription_history',
    'label property' => 'id',
    'permissions' => [
      'view' => [],
      'update' => [],
      'create' => [],
      'delete' => [],
    ],
  ];
}

/**
* Implements hook_views_pre_render().
*/
function clin_waitlist_views_pre_render(ViewExecutable $view) {
  if (isset($view) && ($view->storage->id() == 'waitlist_test')) {
    $view->element['#attached']['library'][] = 'clin_waitlist/table_class';
  }
}
