<?php

use Drupal\webform\Utility\WebformFormHelper;

@require_once 'pe_update_booking.variables.php';
//@require_once __DIR__ . '/../ped_online_course_booking_update/ped_online_course_booking_update.variables.php';

/**
 * Implements hook_form_alter().
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 */
function pe_update_booking_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id == "webform_submission_update_ped_booking_add_form") {

    // Get custom field constants
    $constants = get_defined_constants(FALSE);

    //Attach library
    $form['#attached']['library'][] = 'pe_update_booking/pe_update_booking';
    $form['#attached']['drupalSettings']['ped_booking_update']['start_date'] = '#edit-' . str_replace('_', '-', PED_BOOKING_UPDATE_START_DATE);
    $form['#attached']['drupalSettings']['ped_booking_update']['end_date'] = '#edit-' . str_replace('_', '-', PED_BOOKING_UPDATE_END_DATE);
    
    //Get webform form elements
    $elements = WebformFormHelper::flattenElements($form);
    if (empty($elements)) {
      return;
    }

    //Toggle text field if Presentation Topic is Custom/Something Different
    if ($elements[PE_UPDATE_BOOKING_PRESENTATION_TOPICS]['#default_value'][0] == "CustomSomethingDifferent") {
      $elements[PE_UPDATE_BOOKING_OTHER_PRESENTATION_TOPICS]['#wrapper_attributes']['class'][0] = "";
    }

    //Hide Virtual Session fields if Presentation Method is not Online Presentaion
    if ($elements[PE_UPDATE_BOOKING_PRESENTATION_METHOD]['#default_value'] != 'Online Presentation') {
      $elements[PE_UPDATE_BOOKING_VIRTUAL_SESSION_FIELDSET]['#access'] = FALSE;
    }
    //Get booking type
    $bt = $elements[PE_UPDATE_BOOKING_BOOKING_TYPE]['#default_value'];

    //Youth presentation
    if ($bt == PE_UPDATE_BOOKING_YOUTH_ACTIVITY) {
      //  Presentation topic dropdown options
      $elements[PE_UPDATE_BOOKING_PRESENTATION_TOPICS]['#options'] = [
        'SexualHarassment' => 'Sexual Harassment',
        'SexualAssaultConsent' => 'Sexual Assault & Consent',
        'NonConsensualPhotoSharing' => 'Non-Consensual Photo Sharing',
        'SACEServices' => 'SACE Services',
        'CustomSomethingDifferent' => 'Custom/Unsure',
      ];
    }

    $mapper = ($bt == 204) ? ['Online Meeting', 'In-Person Meeting'] : (($bt == 203) ? ['In-Person Event', 'Online Event'] : ['In-Person Presentation', 'Online Presentation']);
    $options = [];
    foreach($mapper as $value) {
      $options[$value] = $elements['civicrm_1_activity_1_cg2_custom_88']['#options'][$value];
    }
    $elements['civicrm_1_activity_1_cg2_custom_88']['#options'] = $options;

    if ($bt == 203) {
      $elements['civicrm_1_activity_1_cg2_custom_815']['#title'] = 'Approximate number of participants per presentation';
    }

    if (in_array($bt, [57, 55, 59])) {

      //  Presentation method dropdown options
      $elements[PE_UPDATE_BOOKING_DELIVERY_FORMAT]['#options'] = [
        'In-Person Presentation' => 'In-Person Presentation',
        'Online Presentation' => 'Online Presentation',
      ];
      //  Grades and ages
      $elements[PE_UPDATE_BOOKING_GRADES_AND_AGES]['#options'] = [
        'Grade 7 (ages 12-13)' => 'Grade 7 (ages 12-13)',
        'Grade 8 (ages 13-14)' => 'Grade 8 (ages 13-14)',
        'Grade 9 (ages 14-15)' => 'Grade 9 (ages 14-15)',
        'High School (ages 15-18)' => 'High School (ages 15-18)',
      ];
    }
  }
}

function pe_update_booking_preprocess_page_title(&$variables, $hook) {
  $current_path = \Drupal::service('path.current')->getPath();
  if ($current_path == '/webform/update_ped_booking') {
    //Activity ID
    $aid = \Drupal::request()->query->get('aid') ?? 0;
    if (empty($aid) || !is_numeric($aid)) {
      return;
    }

    \Drupal::service('civicrm')->initialize();
    //Get booking type from activity
    $activity = \Civi\Api4\Activity::get(FALSE)
      ->addSelect('activity_type_id')
      ->addWhere('id', '=', $aid)
      ->setLimit(1)
      ->execute();
    $bt = $activity->first()['activity_type_id'];

    if ($bt == PE_UPDATE_BOOKING_YOUTH_ACTIVITY) {
      $variables['title'] = [
        '#markup' => 'Youth Presentation Booking Update Form',
      ];
    }
    elseif ($bt == PE_UPDATE_BOOKING_ADULT_ACTIVITY) {
      $variables['title'] = [
        '#markup' => 'Adult Presentation Booking Update Form',
      ];
    }
    elseif ($bt == 201) {
      $variables['title'] = [
        '#markup' => 'WiseGuyz Booking Update Form',
      ];
    }
    elseif ($bt == 204) { 
      $variables['title'] = [
        '#markup' => 'Institutional Support Booking Update Form',
      ];
    }
    elseif ($bt == 203) {
      $variables['title'] = [
        '#markup' => 'Community Engagement Booking Update Form',
      ];
    }
  }
}
