-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_activity_role`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_activity_role
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE `civicrm_activity_role` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique ActivityRole ID',
  `assignee_contact_id` int unsigned NOT NULL COMMENT 'FK to Contact',
  `role_id` varchar(255) NOT NULL,
  `activity_id` int unsigned NOT NULL COMMENT 'FK to Activity',
  PRIMARY KEY (`id`),
  CONSTRAINT FK_civicrm_activity_role_assignee_contact_id FOREIGN KEY (`assignee_contact_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE CASCADE,
  CONSTRAINT FK_civicrm_activity_role_activity_id FOREIGN KEY (`activity_id`) REFERENCES `civicrm_activity`(`id`) ON DELETE CASCADE
)
ENGINE=InnoDB;
