<?php
use Drupal\webform\Utility\WebformFormHelper;

/**
 * Implements hook_form_alter().
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 */
function ped_booking_request_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id == 'webform_submission_public_education_presentation_bo_add_form') {
    $elements = WebformFormHelper::flattenElements($form);
    $roles = \Drupal::currentUser()->getRoles() ?? [];
    if (!in_array('pe', $roles) && !in_array('pe_tl', $roles)) {
      $elements['markup_01']['#access'] = FALSE;
      $elements['markup_02']['#access'] = TRUE;
    }
    elseif (in_array('pe', $roles) || in_array('pe_tl', $roles)) {
      $elements['markup_01']['#access'] = TRUE;
      $elements['markup_02']['#access'] = FALSE;
    }
  }
}
