-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_locked_note`;

SET FOREIGN_KEY_CHECKS=1;

-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_locked_note
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE `civicrm_locked_note` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique LockedNote ID',
  `note_id` int unsigned COMMENT 'FK to Note',
  `is_locked` TINYINT(1) NOT NULL COMMENT 'Is the note locked for editing?',
  PRIMARY KEY (`id`),
  CONSTRAINT FK_civicrm_locked_note_note_id FOREIGN KEY (`note_id`) REFERENCES `civicrm_note`(`id`) ON DELETE CASCADE)
ENGINE=InnoDB;
