-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_user_team_activity_entity`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_user_team_activity_entity
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE `civicrm_user_team_activity_entity` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique UserTeamActivityEntity ID',
  `activity_type_id` int unsigned COMMENT 'Activity Type ID',
  `user_team` int unsigned COMMENT 'User Team',
  PRIMARY KEY (`id`)
)
ENGINE=InnoDB;

INSERT INTO civicrm_user_team_activity_entity (activity_type_id, user_team) VALUES
(77,52),
(78,52),
(118,52),
(72,52),
(119,52),
(110,52),
(111,52),
(79,124),
(80,124),
(82,124),
(81,124),
(177,124),
(178,124),
(179,124),
(112,124),
(113,124),
(114,124),
(115,125),
(116,125),
(117,125),
(120,125),
(121,125),
(122,125),
(124,125),
(125,125),
(126,125),
(127,125),
(128,125),
(130,125),
(131,125),
(132,43),
(133,43),
(134,43),
(135,43),
(136,43),
(137,43),
(138,43),
(139,43),
(140,43),
(141,57),
(142,57),
(143,57),
(144,57),
(145,57),
(146,57),
(147,42),
(90,126),
(148,126),
(149,126),
(150,126),
(151,126),
(152,126),
(153,126),
(154,126),
(155,126),
(156,126),
(88,126),
(102,126),
(103,126),
(157,126),
(68,127),
(158,127),
(159,127),
(160,127),
(161,127),
(162,127),
(163,127),
(164,41),
(165,41),
(166,41),
(167,41),
(168,41),
(169,41),
(170,41),
(62,12),
(92,12),
(171,12),
(172,40),
(173,40),
(174,40),
(89,40),
(144,40),
(55,39),
(57,39),
(58,39),
(59,39),
(60,39),
(61,39),
(144,39),
(175,39),
(176,128),
(144,128);