<?php

use Drupal\webform\Utility\WebformFormHelper;
use Drupal\webform\Entity\Webform;

@require_once 'clin_update_appointment.variables.php';

/**
 * Implements hook_form_alter().
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 */
function clin_update_appointment_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id == "webform_submission_update_appointment_add_form") {

    //Attach library
    $form['#attached']['library'][] = 'clin_update_appointment/clin_update_appointment';

    // Get webform form elements
    $elements = WebformFormHelper::flattenElements($form);

    $aid = \Drupal::request()->query->get('aid') ?? 0;
    if(!empty($aid) && is_numeric($aid)) {
      \Drupal::service('civicrm')->initialize();
      $activities = \Civi\Api4\Activity::get(FALSE)
      ->addWhere('id', '=', $aid)
      ->setLimit(1)
      ->addChain('parent_activity', \Civi\Api4\Activity::get(FALSE)
        ->addWhere('id', '=', '$parent_id')
        ->addSelect('assignee_contact_id', 'activity_type_id', 'details', 'duration')
      )
      ->execute();

      if(isset($activities[0]['parent_activity'][0])) {
        $parentActivity = $activities[0]['parent_activity'][0]; 
        $elements['activity_type_id']['#default_value'] = $parentActivity['activity_type_id'];
        $elements[CLIN_UPDATE_APP_DURATION]['#default_value'] = $parentActivity['duration'];
        $elements[CLIN_UPDATE_APP_ASSIGNEE_ID]['#default_value'] = $parentActivity['assignee_contact_id'];
      }
    }
  }
}
