-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_multiple_booking`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_multiple_booking
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE `civicrm_multiple_booking` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique MultipleBooking ID',
  `is_multiple_booking` tinyint NOT NULL DEFAULT 0 COMMENT 'Does this activity type support multiple bookings',
  `activity_type_id` int COMMENT 'Activity Type ID',
  `booking_calendar_display` tinyint NOT NULL DEFAULT 0 COMMENT 'Should this activity type be shown on the booking calendars',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UI_activity_type_id`(activity_type_id)
)
ENGINE=InnoDB;
