<?php

use Drupal\webform\Utility\WebformFormHelper;

@require_once 'clin_intake_adult_data.variables.php';

/**
 * Implements hook_form_alter().
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 */
function clin_intake_adult_data_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id == "clin_adult_intake_data") {
    // Get custom field constants
    $constants = get_defined_constants(FALSE);

    //Attach library
    $form['#attached']['library'][] = 'clin_intake_adult_data/clin_intake_adult_data';

    $aid = \Drupal::request()->query->get('aid') ?? 0;
    if (empty($aid) || !is_numeric($aid)) {
      return;
    }
    else {
      \Drupal::service('civicrm')->initialize();
      //Get booking type from activity
      $activityRef = \Civi\Api4\Activity::get(FALSE)
        ->addWhere('id', '=', $aid)
        ->setLimit(1)
        ->execute();
      $activityRef = $activityRef->first();

      //Get webform form elements
      $elements = WebformFormHelper::flattenElements($form);
      if (empty($elements)) {
        return;
      }

      $elements[CLIN_INTAKE_ADULT_DATA_INITIAL_CALL]['#default_value'] = $activityRef['created_date'];
      $elements[CLIN_INTAKE_ADULT_DATA_INTAKE_NUMBER]['#default_value'] = $aid;
    }

  }
}
