<?php
// set my base_url based on some environment settings, and redirect to it if necessary.
// my hostname is generated by docker
// get my db settings from $_ENV
// error_reporting(E_ALL & ~E_NOTICE & ~E_STRICT & ~E_DEPRECATED);
if (!empty($_ENV['DRUPAL_DATABASE'])) {
  $databases = array (
    'default' =>
    array (
      'default' =>
      array (
        'database' => $_ENV['DRUPAL_DATABASE'],
        'username' => $_ENV['MYSQL_USER'],
        'password' => $_ENV['MYSQL_PASSWORD'],
        'host' => 'vsql',
        'port' => '3306',
        'driver' => 'mysql',
        'prefix' => '',
        'namespace' => 'Drupal\\Core\\Database\\Driver\\mysql',
      ),
    ),
  );
}

$base_host = $_ENV['VSITE'].'.f.civicrm.ca';
if (!empty($_ENV['VSITE_DOMAIN'])) { // && !empty($_SERVER['HTTP_HOST'])) {
  if ($_SERVER['HTTP_HOST'] != $base_host) {
    $base_host = $_ENV['VSITE_DOMAIN'];
    // die($base_host .' '.$_SERVER['HTTP_HOST']);
  }
}
// redirect to VSITE_DOMAIN if set and not cli
if ($_SERVER['HTTP_HOST'] != $base_host 
  && !empty($_ENV['VSITE_DOMAIN'])
  && (php_sapi_name() !== 'cli')
) {
  header('Location: https://'.$base_host.$_SERVER['REQUEST_URI']);
  exit();
}
// add more memory when using cli (drush/cv)
if (php_sapi_name() === 'cli') {
  ini_set('memory_limit','1024M');
}
$base_url = 'https://'.$base_host;
// use varnish and redis unless I haven't yet created the settings file.
if (!empty($databases)) {
  //include 'sites/all/host/e.varnish.inc';
  //include 'sites/all/host/e.redis.inc';
  // Also use Redis in CiviCRM
  if (!empty($_ENV['HOSTNAME'])) {
    //include 'sites/all/host/e.civicrm.inc';
  }
  global $civicrm_paths;
  $civicrm_paths['civicrm.root']['url'] = 'https://'. $_ENV['VSITE_DOMAIN'].'/libraries/civicrm/';
  // define( 'CIVICRM_UF_BASEURL', $base_url . '/');
}
$settings['trusted_host_patterns'][] = 'civicrm\.ca$';
$settings['trusted_host_patterns'][] = preg_quote($base_host);

// $bridge_ip = gethostbyname('varnish');
// $swarm_ip = '10.255.0.2'; // ,10.255.0.2';
$swarm_ip = '10.255.0.2'; // ,10.255.0.2';
// $host_ip = '209.15.202.141';
$conf['reverse_proxy'] = TRUE;
// $conf['reverse_proxy_addresses'] = array($host_ip, $swarm_ip, $bridge_ip);
$conf['reverse_proxy_addresses'] = array($swarm_ip);
$conf['reverse_proxy_header'] = 'HTTP_X_FORWARDED_FOR';
// turn off opcache for dev/preproduction/etc.
//if (
//  !empty($_ENV['VSITE_ENVIRONMENT'])
//  && 'Production' != $_ENV['VSITE_ENVIRONMENT']
//  && 'Staging' != $_ENV['VSITE_ENVIRONMENT']
//  ) {
//  ini_set('opcache.enable', 0);
//} 
~           
