-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_activity_type_program`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_activity_type_program
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE `civicrm_activity_type_program` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique ActivityTypeProgram ID',
  `activity_type_id` int unsigned COMMENT 'Activity Type ID',
  `user_team_id` int unsigned COMMENT 'User Team ID',
  PRIMARY KEY (`id`)
)
ENGINE=InnoDB;
