<?php
use Drupal\webform\Utility\WebformFormHelper;
require_once 'ped_booking_request.variables.php';

/**
 * Implements hook_form_alter().
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 */
function ped_booking_request_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id == 'webform_submission_public_education_presentation_bo_add_form') {
    $elements = WebformFormHelper::flattenElements($form);
    $roles = \Drupal::currentUser()->getRoles();

    if (!in_array('pe', $roles) && !in_array('pe_tl', $roles)) {
      $elements['markup_01']['#access'] = FALSE;
      $elements['markup_02']['#access'] = TRUE;
    }
    else {
      $elements['markup_01']['#access'] = TRUE;
      $elements['markup_02']['#access'] = FALSE;
    }
  }
  if ($form_id == "webform_submission_ped_booking_request_query_params_add_form") {
    //attach js
    $form['#attached']['library'][] = 'ped_booking_request/ped_booking_request';

    $bt = \Drupal::request()->query->get('booking_type');
    $elements = WebformFormHelper::flattenElements($form);  

    if (in_array($bt, [PED_BOOKING_REQUEST_COMMUNITY_ENGAGEMENT_ACTIVITY, PED_BOOKING_REQUEST_INSTITUTIONAL_SUPPORT_ACTIVITY, PED_BOOKING_REQUEST_WISEGUYZ_ACTIVITY])) {
      unset($elements[PED_BOOKING_REQUEST_DELIVERY_FORMAT]['#options']['Online Course']);
      if ($bt == PED_BOOKING_REQUEST_COMMUNITY_ENGAGEMENT_ACTIVITY) {
        $elements[PED_BOOKING_REQUEST_NUMBER_PARTICIPANTS]['#title'] = 'Approximate number of attendees';
        $elements[PED_BOOKING_REQUEST_PREFERRED_DATES]['#description']['#markup'] = '<p>Please list your event date if known, and note that bookings are subject to staff availability. We will make every effort to meet requests, but if you are flexible with your dates, please provide this detail.</p>';
      }
    }
    if ($bt == 58 || $bt == PED_BOOKING_REQUEST_YOUTH_ACTIVITY) {
      $elements[PED_BOOKING_REQUEST_YOUR_ORGANIZATION]['#title'] = 'Your School';
      $elements[PED_BOOKING_REQUEST_YOUR_ORGANIZATION]['#description']['#markup'] = str_replace('organization', 'school', $elements[PED_BOOKING_REQUEST_YOUR_ORGANIZATION]['#description']['#markup']);
      $elements[PED_BOOKING_REQUEST_ORGANIZATION_NAME]['#title'] = 'School Name';
      $elements[PED_BOOKING_REQUEST_ORGANIZATION_EMAIL]['#description']['#markup'] = str_replace('organization', 'school', $elements[PED_BOOKING_REQUEST_ORGANIZATION_EMAIL]['#description']['#markup']);
      $elements[PED_BOOKING_REQUEST_NEW_ORGANIZATION_FIELDSET]['#title'] = 'New School';
      $elements[PED_BOOKING_REQUEST_NEW_ORGANIZATION_TYPE]['#default_value'] = $elements['civicrm_3_contact_1_contact_contact_sub_type']['#options'];
      $elements[PED_BOOKING_REQUEST_TOPICS_MARKUP]['#text'] = '<h2><span style="color:#2e416c;"><strong>Booking Details</strong></span></h2>
        <h3><span style="color:#2e416c;"><strong>Presentation Topic(s)</strong></span></h3>
        <p>The typical presentation topics by approximate age range are listed below. For more information about each presentation topic, please visit <a href="https://www.sace.ca/services/public-education">www.sace.ca/services/public-education</a>.</p>
        <ul>
          <li>Gr 7/12-13 years - Sexual Harassment</li>
          <li>Gr 8/13-14 years&nbsp;- Sexual Assault &amp; Consent</li>
          <li>Gr 9/14-15 years - Non-Consensual Photo Sharing</li>
          <li>High School/15-18 years - Sexual Assault &amp; Consent and/or Non-Consensual Photo Sharing  </li>
        </ul>      
        <div class="notranslate" style="all: initial;">&nbsp;</div>';
    }
    if($bt == PED_BOOKING_REQUEST_YOUTH_ACTIVITY) {
      //  Presentation topic dropdown options
      $elements[PED_BOOKING_REQUEST_PRESENTATION_TOPIC]['#options'] = [
        'SexualHarassment' => 'Sexual Harassment',
        'SexualAssaultConsent' => 'Sexual Assault & Consent',
        'NonConsensualPhotoSharing' => 'Non-Consensual Photo Sharing',
        'SACEServices' => 'SACE Services',
        'CustomSomethingDifferent' => 'Custom/Something Different'
      ];
    }
    if (in_array($bt, [PED_BOOKING_REQUEST_YOUTH_ACTIVITY, PED_BOOKING_REQUEST_ADULT_ACTIVITY])){
      $elements[PED_BOOKING_REQUEST_SESSIONS_MARKUP]['#text'] = str_replace('Your Session(s)', 'Presentation Details', $elements[PED_BOOKING_REQUEST_SESSIONS_MARKUP]['#text']);      
      
      //  Presentation method dropdown options
      $elements[PED_BOOKING_REQUEST_DELIVERY_FORMAT]['#options'] = [
        'In-Person Presentation' => 'In-Person Presentation',
        'Online Presentation' => 'Online Presentation',
      ];
      //  Grades and ages
      $elements[PED_BOOKING_REQUEST_GRADES_AND_AGES]['#options'] = [
        'Grade 7 (ages 12-13)' => 'Grade 7 (ages 12-13)',
        'Grade 8 (ages 13-14)' => 'Grade 8 (ages 13-14)',
        'Grade 9 (ages 14-15)' => 'Grade 9 (ages 14-15)',
        'High School (ages 15-18)' => 'High School (ages 15-18)'
       ];
       // update title for approx number of participants
       $elements[PED_BOOKING_REQUEST_NUMBER_PARTICIPANTS]['#title'] = 'Approximate number of participants per presentation';

       // update title for how many presentations
       $elements[PED_BOOKING_REQUEST_NUMBER_SESSIONS]['#title'] = 'How many presentations would you like?';        
    }

    if($bt == PED_BOOKING_REQUEST_ADULT_ACTIVITY) {
      // update presentation topics dropdown options
      $elements[PED_BOOKING_REQUEST_PRESENTATION_TOPIC]['#options'] = [
        'SexualHarassment' => 'Sexual Harassment',
        'SexualAssaultConsent' => 'Sexual Assault & Consent',
        'NonConsensualPhotoSharing' => 'Non-Consensual Photo Sharing',
        'TechnologyFacilitatedSexualViolence' => 'Technology-Facilitated Sexual Violence',
        'SACEServices' => 'SACE Services',
        'BystanderIntervention' => 'Bystander Intervention',
        'CreatingSaferSpacesandRespondingtoSexualViolence' => 'Creating Safer Spaces & Responding to Sexual Violence',
        'SupportiveResponsestoSexualViolence' => 'Supportive Responses to Sexual Violence',
        'SexualViolenceTrauma' => 'Sexual Violence Trauma',
        'DomesticViolence' => 'Domestic Violence',
        'ChildSexualAbuse' => 'Child Sexual Abuse',
        'CustomSomethingDifferent' => 'Custom/Something Different'

      ];
    }
  }
}

function ped_booking_request_preprocess_page_title(&$variables, $hook) {
  $current_path = \Drupal::service('path.current')->getPath();
  
  if($current_path == '/webform/ped_booking_request_query_params') {
    $bt = \Drupal::request()->query->get('booking_type') ?? 0;
    if($bt == PED_BOOKING_REQUEST_YOUTH_ACTIVITY) {
      $variables['title'] = [
        '#markup' => 'Youth Presentation Booking Request',
      ];
    }
    elseif($bt == PED_BOOKING_REQUEST_ADULT_ACTIVITY) {
      $variables['title'] = [
        '#markup' => 'Adult Presentation Booking Request',
      ];
    }
  }
}