<?php

/**
 * @file
 * This module allows testing if hook_nagios still works.
 */

use Drupal\Core\Url;

/**
 * Implements hook_nagios_info().
 *
 * For more details please read the section 'API' section within README.txt.
 */
function nagios_hook_test_module_nagios_info(): array {
  return [
    'name' => 'nagios_hook_test_module',
    'id' => 'NAGIOS_CHECK_KEY',
  ];
}

/**
 * Implements hook_nagios().
 */
function nagios_hook_test_module_nagios(): array {
  return [
    'NAGIOS_CHECK_KEY' => [
      // 1 means NAGIOS_STATUS_WARNING.
      'status' => 1,
      'type' => 'state',
      'text' => 'Text description for the problem',
    ],
  ];
}

/**
 * Implements hook_requirements().
 */
function nagios_hook_test_module_requirements(): array {
  $url = Url::fromRoute('nagios.ignored_modules');
  $url->setAbsolute();

  return [
    'big_example_problem' => [
      'title' => 'Nagios Hook Test Module',
      'value' => 'This is an example error.',
      'severity' => REQUIREMENT_ERROR,
      'description' => 'This hook exists to play with IgnoredModulesForm at ' . $url->toString(),
    ],
  ];
}
