-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_appointment_notes`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_appointment_notes
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE `civicrm_appointment_notes` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique AppointmentNotes ID',
  `note_id` int unsigned COMMENT 'Note ID',
  `attachment_id` int unsigned COMMENT 'Attachment ID',
  PRIMARY KEY (`id`)
)
ENGINE=InnoDB;
