<?php

use Drupal\views\ViewExecutable;
use Drupal\views\Plugin\views\query\QueryPluginBase;


function clin_client_profile_preprocess_page(&$variables) {
  $current_path = \Drupal::service('path.current')->getPath();
  $pattern = '/\/contact-information(?:\/[\w-]+)*\/(\d+)/';
  // Add JS to /client-home pages
  if (preg_match($pattern, $current_path, $matches)) {
    $variables['#attached']['library'][] = 'clin_client_profile/clin_client_profile';
  }
}
