<?php

use Drupal\webform\Utility\WebformFormHelper;

/**
 * Implements hook_form_alter().
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 */
function clin_client_profile_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id == "webform_submission_client_profile_add_form") {
    // Get custom field constants
    $constants = get_defined_constants(FALSE);

    //Attach library
    $form['#attached']['library'][] = 'clin_client_profile/clin_client_profile';

    $cid = \Drupal::request()->query->get('cid') ?? 0;
    if (!empty($cid) && is_numeric($cid)) {
      \Drupal::service('civicrm')->initialize();
      // Get contact information
      $contact = \Civi\Api4\Contact::get(FALSE)
        ->addWhere('id', '=', $cid)
        ->setLimit(1)
        ->execute()
        ->first();

      // Get webform form elements
      $elements = WebformFormHelper::flattenElements($form);
      if (!empty($elements)) {
        $elements[CLIN_CLIENT_PROFILE_CLIENT_ID]['#default_value'] = $cid;
      }
    }
  }
}
