<?php

use Drupal\webform\Utility\WebformFormHelper;

/**
 * Implements hook_form_alter().
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 */
function community_engagement_services_request_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  //attach js
  if ($form_id == "webform_submission_ce_services_request_add_form") {
    $form['#attached']['library'][] = 'community_engagement_services_request/community_engagement_services_request';
  }
}
