<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from saceflags/xml/schema/CRM/Saceflags/Saceflags.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:9ae3f44341a485dab5a491dc603f7707)
 */
use CRM_Saceflags_ExtensionUtil as E;

/**
 * Database access object for the Saceflags entity.
 */
class CRM_Saceflags_DAO_Saceflags extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_saceflags';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique Saceflags ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * Activity Type
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $activity_type_id;

  /**
   * Used for flagging contacts?
   *
   * @var bool|null
   *   (SQL type: text)
   *   Note that values will be retrieved from the database as a string.
   */
  public $used_for_flagging_contacts;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_saceflags';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Appointment Colourses') : E::ts('Appointment Colours');
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('Unique Saceflags ID'),
          'required' => TRUE,
          'where' => 'civicrm_saceflags.id',
          'table_name' => 'civicrm_saceflags',
          'entity' => 'Saceflags',
          'bao' => 'CRM_Saceflags_DAO_Saceflags',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'activity_type_id' => [
          'name' => 'activity_type_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('Activity Type'),
          'where' => 'civicrm_saceflags.activity_type_id',
          'table_name' => 'civicrm_saceflags',
          'entity' => 'Saceflags',
          'bao' => 'CRM_Saceflags_DAO_Saceflags',
          'localizable' => 0,
          'add' => NULL,
        ],
        'used_for_flagging_contacts' => [
          'name' => 'used_for_flagging_contacts',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => E::ts('Used for flagging contacts?'),
          'description' => E::ts('Used for flagging contacts?'),
          'where' => 'civicrm_saceflags.used_for_flagging_contacts',
          'table_name' => 'civicrm_saceflags',
          'entity' => 'Saceflags',
          'bao' => 'CRM_Saceflags_DAO_Saceflags',
          'localizable' => 0,
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'saceflags', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'saceflags', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
