<?php
/**
 * Implements hook_form_alter().
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 */
function ped_online_course_booking_request_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {  
  //attach js  
  if($form_id == "webform_submission_ped_online_booking_request_add_form"){
    $form['#attached']['library'][] = 'ped_online_course_booking_request/ped_online_course_booking_request';
  }
}