<?php
use Drupal\webform\Utility\WebformFormHelper;

/**
 * Implements hook_form_alter().
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 */
function external_appointment_booking_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id == 'webform_submission_external_appointment_booking_for_add_form') {
    // Get custom field constants
    $constants = get_defined_constants(FALSE);

    $form['#attached']['drupalSettings']['external_appointment_booking']['start_date'] = '#edit-' . str_replace('_', '-', $constants['Start_Date']);
    $form['#attached']['drupalSettings']['external_appointment_booking']['end_date'] = '#edit-' . str_replace('_', '-', $constants['End_Date']);
    $form['#attached']['library'][] = 'external_appointment_booking/external_appointment_booking';
    $form['#attached']['drupalSettings']['external_appointment_booking']['external_appointment_booking']['test'] = 'values';

    //Get webform form elements
    $elements = WebformFormHelper::flattenElements($form);

  }
}
