<?php

use Drupal\webform\Utility\WebformFormHelper;
use Drupal\webform\Entity\Webform;

function clin_add_note_preprocess_page_title(&$variables, $hook) {
  $current_path = \Drupal::service('path.current')->getPath();
  if ($current_path == '/webform/add_note') {
    
    \Drupal::service('civicrm')->initialize();

    // Get aid or nid from url
    $aid = \Drupal::request()->query->get('aid') ?? 0;
    if (empty($aid) || !is_numeric($aid)) {
      $nid = \Drupal::request()->query->get('nid') ?? 0;
      if (empty($nid) || !is_numeric($nid)) {
        $cid = \Drupal::request()->query->get('aid') ?? 0;
        if (empty($cid) || !is_numeric($cid)) {
          return;
        }

        $client = \Civi\Api4\Contact::get(FALSE)
          ->addSelect('display_name')
          ->addWhere('id', '=', $cid)
          ->setLimit(1)
          ->execute()
          ->first();
  
        $variables['title'] = [
          '#markup' => 'Add Note to '.$client['display_name'],
        ];
        
      }
      $note = \Civi\Api4\Note::get(FALSE)
      ->addSelect('subject')
      ->addWhere('id', '=', $nid)
      ->setLimit(1)
      ->execute()
      ->first();

      $variables['title'] = [
        '#markup' => 'Add Note to '.$note['subject'],
      ];
      return;
    }

    //Get activity type from activity
    $activity = \Civi\Api4\Activity::get(FALSE)
      ->addSelect('activity_type_id:name')
      ->addWhere('id', '=', $aid)
      ->setLimit(1)
      ->execute()
      ->first();

      $variables['title'] = [
        '#markup' => 'Add Note to '.$activity['activity_type_id:name'],
      ];
  }
}


function clin_add_note_civicrm_alter_drupal_entities(&$civicrm_entity_info) {
  $civicrm_entity_info['civicrm_entity_file'] = [
    'civicrm entity label' => ts('EntityFile'),
    'civicrm entity name' => 'entity_file',
    'label property' => 'id',
    'permissions' => [
      'view' => [],
      'update' => [],
      'create' => [],
      'delete' => [],
    ],
  ];
}
