-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_booking_import_log`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_booking_import_log
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE `civicrm_booking_import_log` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique BookingImportLog ID',
  `activity_id` int unsigned COMMENT 'FK to Activity',
  `table_name` varchar(255),
  `legacy_id` int unsigned COMMENT 'Spreadsheet Row number',
  PRIMARY KEY (`id`),
  CONSTRAINT FK_civicrm_booking_import_log_activity_id FOREIGN KEY (`activity_id`) REFERENCES `civicrm_activity`(`id`) ON DELETE CASCADE
)
ENGINE=InnoDB;
