<?php

use Drupal\webform\Utility\WebformFormHelper;

@require_once 'clin_intake_cy_data.variables.php';

/**
 * Implements hook_form_alter().
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 */
function clin_intake_cy_data_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id == "webform_submission_clin_c_y_intake_data_add_form") {
    // Get custom field constants
    $constants = get_defined_constants(FALSE);

    //Attach library
    $form['#attached']['library'][] = 'clin_c_y_intake_data/clin_c_y_intake_data';

    $aid = \Drupal::request()->query->get('aid') ?? 0;
    if (empty($aid) || !is_numeric($aid)) {
      return;
    }
    else {
      \Drupal::service('civicrm')->initialize();
      //Get booking type from activity
      $activityRef = \Civi\Api4\Activity::get(FALSE)
        ->addWhere('id', '=', $aid)
        ->setLimit(1)
        ->execute();
      $activityRef = $activityRef->first();

      //Get webform form elements
      $elements = WebformFormHelper::flattenElements($form);
      if (empty($elements)) {
        return;
      }

      $elements[CLIN_INTAKE_ADULT_DATA_INITIAL_CALL]['#default_value'] = $activityRef['created_date'];
      $elements[CLIN_INTAKE_ADULT_DATA_INTAKE_NUMBER]['#default_value'] = $aid;
    }
  }
}

// function clin_intake_booking_update_preprocess_page_title(&$variables, $hook) {
//   $current_path = \Drupal::service('path.current')->getPath();
//   if ($current_path == '/webform/clin_intake_cy_data') {
//     //Activity ID
//     $aid = \Drupal::request()->query->get('aid') ?? 0;
//     if (empty($aid) || !is_numeric($aid)) {
//       return;
//     }

//     \Drupal::service('civicrm')->initialize();
//     //Get booking type from activity
//     $activity = \Civi\Api4\Activity::get(FALSE)
//       ->addSelect('activity_type_id')
//       ->addWhere('id', '=', $aid)
//       ->setLimit(1)
//       ->execute();
//     $bt = $activity->first()['activity_type_id'];
//   }
// }
