<?php

use Drupal\webform\Utility\WebformFormHelper;
use Drupal\webform\Entity\Webform;

/**
 * Implements hook_form_alter().
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 */
function clin_flags_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id == "webform_submission_add_flag_add_form") {

    //Attach library
    $form['#attached']['library'][] = 'clin_add_flag/clin_add_flag';

    // Get webform form elements
    $elements = WebformFormHelper::flattenElements($form);
    
    }
}
