<?php

use CRM_Cdntaxreceipts_ExtensionUtil as E;

return [
  [
    'name' => 'job_cdntaxreceipts_deleteoldpdfs',
    'entity' => 'Job',
    'cleanup' => 'always',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'match' => ['name'],
      'values' => [
        'is_active' => TRUE,
        'name' => 'Cdntaxreceipts: Delete old pdfs',
        'description' => E::ts('Delete pdfs that were generated by the queue process.'),
        'run_frequency' => 'Daily',
        'api_entity' => 'CdntaxreceiptsJob',
        'api_action' => 'DeleteOldPdfs',
        'parameters' => 'version=4
        daysToKeep=7',
      ],
    ],
  ],
];
