<?php

use Drupal\webform\Utility\WebformFormHelper;

/**
 * Implements hook_form_alter().
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 */
function clin_intake_booking_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id == "webform_submission_book_intake_add_form") {
    // initialize CiviCRM
    \Drupal::service('civicrm')->initialize();
    $manager = \Civi::resources();
    $manager->addCoreResources();
  
    //Attach library
    $form['#attached']['library'][] = 'clin_intake_booking/clin_intake_booking';
  }
}
